'use strict';
(()=>{
const $=id=>document.getElementById(id),SAVE='tomorrow-open-save-v3',DIRECTIONS={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},clone=o=>JSON.parse(JSON.stringify(o));
let state=fresh(),mode='title',dialog=null,path=[],pendingObject=null,keys=new Set(),camera={x:0,y:0},trail=[],waypoint=null,lastTime=0,walkClock=0,portalCooldown=0,toastTimer,modalFocus,audioContext,soundOn=false,saveClock=0;
const canvas=$('world'),ctx=canvas.getContext('2d');
function fresh(){return {version:3,chapter:0,map:'sugar',pos:{x:16,y:22},dir:'down',walkFrame:1,steps:0,known:['isles','sugar'],clues:[],sides:[],records:TALE.cases.map(()=>({started:false,route:null,decision:null,completed:false})),flags:{archiveDoor:false},endings:[],checkpoints:[],playSeconds:0};}
function cleanSave(raw,withPoints=true){if(!raw||raw.version!==3)throw Error('这是新版探秘旅程的存档入口。旧版存档仍保留在原浏览器中，不能直接转换剧情。');if(!Number.isInteger(raw.chapter)||raw.chapter<0||raw.chapter>8||!WORLD.maps[raw.map])throw Error('存档中的章节或地图无效。');const m=WORLD.maps[raw.map];if(!raw.pos||!Number.isFinite(raw.pos.x)||!Number.isFinite(raw.pos.y)||!WORLD.passable(m,Math.round(raw.pos.x),Math.round(raw.pos.y)))throw Error('存档中的落脚位置无效。');if(!Array.isArray(raw.records)||raw.records.length!==8)throw Error('存档缺少案件记录。');const s=fresh();s.chapter=raw.chapter;s.map=raw.map;s.pos={x:raw.pos.x,y:raw.pos.y};s.dir=DIRECTIONS[raw.dir]?raw.dir:'down';s.steps=Math.max(0,Number(raw.steps)||0);s.playSeconds=Math.max(0,Number(raw.playSeconds)||0);
 s.records=raw.records.map((r,i)=>{if(!r||![null,0,1].includes(r.route)||![null,0,1,2].includes(r.decision)||typeof r.started!=='boolean'||typeof r.completed!=='boolean'||(r.started&&r.route===null)||(i<raw.chapter&&(!r.completed||r.decision===null))||(i>=raw.chapter&&r.completed)||(i>raw.chapter&&(r.started||r.route!==null||r.decision!==null)))throw Error('存档的分歧顺序不完整。');return {started:r.started,route:r.route,decision:r.decision,completed:r.completed};});
 for(const [key,valid]of [['clues',Object.keys(TALE.clues)],['sides',TALE.sides.map(x=>x.id)],['endings',TALE.endings.map(x=>x.id)],['known',Object.keys(WORLD.maps)]]){if(!Array.isArray(raw[key])||raw[key].some(x=>!valid.includes(x)))throw Error('存档包含未知记录。');s[key]=[...new Set(raw[key])];}if(s.clues.some(id=>TALE.clues[id].case>s.chapter))throw Error('存档含有尚未发生的线索。');for(let i=0;i<s.chapter;i++)if(required(i,s).some(id=>!s.clues.includes(id)))throw Error('存档缺少已完成案件的线索。');s.flags={archiveDoor:raw.flags?.archiveDoor===true};
 if(withPoints&&Array.isArray(raw.checkpoints))s.checkpoints=raw.checkpoints.slice(0,16).map(p=>{if(!Number.isInteger(p.chapter)||p.chapter<0||p.chapter>7||!['route','decision'].includes(p.kind))throw Error('回溯记录无效。');return {chapter:p.chapter,kind:p.kind,snapshot:cleanSave(p.snapshot,false)};});return s;
}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));$('saveState').textContent='已保存';}catch{$('saveState').textContent='保存失败，请导出备份';}updateContinue();}
function updateContinue(){try{$('continueGame').hidden=!localStorage.getItem(SAVE);$('continueGame').disabled=!Art.ready;}catch{$('continueGame').hidden=true;}}
function checkpoint(kind){const i=state.chapter;if(state.checkpoints.some(p=>p.chapter===i&&p.kind===kind))return;const snap=clone({...state,checkpoints:[],endings:[]});state.checkpoints.push({chapter:i,kind,snapshot:snap});}
function rewind(index){const point=state.checkpoints[index];if(!point)return;const endings=[...state.endings],points=state.checkpoints.slice(0,index);state=cleanSave(point.snapshot,false);state.endings=endings;state.checkpoints=points;mode='world';path=[];trail=[];waypoint=null;closeModal();save();hud();toast('已回到第 '+(state.chapter+1)+' 案。后续剧情已撤回，已看结局保留在收藏中。');}
function required(i=state.chapter,s=state){const c=TALE.cases[i];return c?[...c.common,...(s.records[i].route===null?[]:[c.routes[s.records[i].route].clue])]:[];}
function tags(){return state.records.flatMap((r,i)=>r.completed?TALE.cases[i].decisions[r.decision].tags:[]);}
function endingAllowed(e){const r=state.records,d=i=>r[i].decision,t=tags();switch(e.condition){case'always':return true;case'manual':return d(6)===1||t.filter(x=>x==='manual').length>=2;case'public':return (d(1)===0||d(4)===0)&&t.includes('record');case'holiday':return [1,2].includes(d(0))&&[0,2].includes(d(5));case'leave':return d(3)===2||d(2)===2;case'trial':return d(6)===2&&state.sides.length>=4;default:return false;}}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4300);}
function objective(){const c=TALE.cases[state.chapter];if(!c)return {map:'council',x:16,y:15,text:'回昼务城的临时议事厅，在空白公告板前安排明天。'};const r=state.records[state.chapter],host=WORLD.maps[c.hostMap].objects.find(o=>o.id===c.hostId);if(!r.started)return {map:c.hostMap,...host,text:'去'+WORLD.maps[c.hostMap].name+'，找'+TALE.people[c.host].name+'聊聊。'};const missing=required().find(id=>!state.clues.includes(id));if(missing)return {...WORLD.cluePlaces[missing],text:'查看'+WORLD.maps[WORLD.cluePlaces[missing].map].name+'的「'+TALE.clues[missing].title+'」。'};return {map:c.hostMap,...host,text:'线索齐了，回去找'+TALE.people[c.host].name+'，商量今天怎么办。'};}
function hud(){const c=TALE.cases[state.chapter];$('caseNumber').textContent=c?'第 '+String(state.chapter+1).padStart(2,'0')+' 案 / 08':'明天的安排';$('caseTitle').textContent=c?.title||'故事还没有替你结束';$('breadcrumbs').textContent=WORLD.ancestors(state.map).join(' › ');$('miniLabel').textContent=WORLD.maps[state.map].name;$('goalText').textContent=objective().text;$('clueStrip').replaceChildren();if(c)for(let n=0;n<3;n++){let el=document.createElement('span'),id=required()[n],found=id&&state.clues.includes(id);el.textContent=found?'✓ '+(n+1):'· '+(n+1);el.className=found?'found':'';el.title=id?TALE.clues[id].title:'先商量调查路线';$('clueStrip').append(el);}else $('clueStrip').textContent='八案已完成';}
function start(s){state=s;mode='world';path=[];trail=[];waypoint=null;$('titleScreen').hidden=true;$('playScreen').hidden=false;closeModal();resize();hud();showMapName();canvas.focus({preventScroll:true});}
function showMapName(){$('mapName').textContent=WORLD.maps[state.map].name;$('mapName').hidden=false;setTimeout(()=>$('mapName').hidden=true,1700);}
function talk(lines,done=()=>{},question=null,options=null){keys.clear();path=[];pendingObject=null;mode='dialogue';$('nearHint').hidden=true;dialog={lines:lines.length?lines:[['旁白','……']],at:0,done,question,options};$('dialogue').hidden=false;renderLine();}
function renderLine(){if(!dialog)return;const [who,text]=dialog.lines[dialog.at];$('speaker').textContent=who;$('dialogueText').textContent=text;$('lineCount').textContent=(dialog.at+1)+' / '+dialog.lines.length;$('choices').replaceChildren();$('nextLine').hidden=false;$('readSegment').hidden=dialog.at===dialog.lines.length-1;const person=Object.keys(TALE.people).find(id=>TALE.people[id].name===who);$('portrait').hidden=!person;if(person)Art.portrait($('portrait'),person);$('dialogue').scrollTop=0;}
function next(){if(!dialog)return;if(dialog.at<dialog.lines.length-1){dialog.at++;renderLine();return;}if(dialog.options){$('dialogueText').textContent=dialog.question;$('portrait').hidden=true;$('lineCount').textContent='亲自决定';$('nextLine').hidden=true;$('readSegment').hidden=true;$('choices').replaceChildren();for(const opt of dialog.options){const b=document.createElement('button');b.textContent=opt.label;b.onclick=()=>{const action=opt.action;endTalk();action();};$('choices').append(b);}return;}const done=dialog.done;endTalk();done();}
function endTalk(){dialog=null;mode='world';$('dialogue').hidden=true;keys.clear();canvas.focus({preventScroll:true});}
function conditionalEcho(i){const r=state.records,d=j=>r[j].decision;if(i===1)return [['鹤见',d(0)===2?'听说你们把智能门改成了把手。我们的表格没有“降级成功”，暂时记在创新栏。':'早餐铺的排班改了。我们正研究那算设备调整，还是一次还没命名的协商。']];if(i===4)return [['鹤见',d(1)===0?'上次你公开了公告的修改记录，所以岗位规则也已经备好。请监督，别只监督打印机。':'我们按流程给了摘要。烬说摘要少的恰好是责任人。我会把原件一并给你。']];if(i===5)return [['七',d(3)===2?'听说零搬出去了。共享一段过去，不会替后来的一切作决定。':'铃和零的安排我看过了。如果换成我的备份，我还没有想好希望怎么办。']];if(i===7)return [['烬',TALE.cases[6].decisions[d(6)].after],['澪','我们留下的安排会限制今天可选的方案。谁也不能靠最后一句漂亮话，把前面的麻烦全部抹掉。']];return [];}
function hostEvent(){const i=state.chapter,c=TALE.cases[i],r=state.records[i];if(!r.started){checkpoint('route');talk([...conditionalEcho(i),...c.brief],()=>{},c.routeQuestion,c.routes.map((o,j)=>({label:o.label,action:()=>{r.started=true;r.route=j;talk(o.lines,()=>{save();hud();toast('调查路线记好了。发光的小物件可以查看。');});}})));return;}if(required().some(id=>!state.clues.includes(id))){talk([[TALE.people[c.host].name,'先把那几件小事看完，再回来商量。'],['澪',objective().text]]);return;}checkpoint('decision');talk(c.confrontation,()=>{},'今天先怎么办？',c.decisions.map((o,j)=>({label:o.label,action:()=>{talk([...o.lines,...c.coda],()=>{r.decision=j;r.completed=true;state.chapter=i+1;save();hud();toast(c.lead);});}})));}
function interact(o){if(mode!=='world'||!o)return;if(o.type==='portal'){const reason=WORLD.portalAllowed(o,state);if(reason){if(o.puzzle&&state.chapter>=4&&(state.chapter>4||state.records[4]?.route===1)){if(!state.clues.includes('origin_clock')){talk([['烬','这里要填一个下班时间。大厅的旧时钟也许还记得。']]);return;}talk([['烬','门上的题目是“请填最后一班原型员工的下班时间”。别填“永远”，它会真的当真。']],()=>{},'拨动旧时钟', ['08:17','17:10','永不下班'].map((label,i)=>({label,action:()=>{if(i===1){state.flags.archiveDoor=true;save();warp(o);}else talk([['门槛',i===2?'这答案曾经很受管理层欢迎。现在不受这扇门欢迎。':'这是上班时间。你已经替他们多上了一天班。']]);}})));}else toast(reason);return;}warp(o);return;}
 if(o.type==='npc'){const c=TALE.cases[state.chapter];if(c&&state.map===c.hostMap&&o.id===c.hostId){hostEvent();return;}talk([[TALE.people[o.person].name,TALE.people[o.person].hello]]);return;}
 if(o.type==='clue'){const c=TALE.clues[o.id],r=state.records[c.case];if(c.case>state.chapter){talk([['凡少','这张纸看起来很要紧。不过现在还不知道该问它什么。']]);return;}if(c.case===state.chapter&&!r.started){talk([['澪','先和这里的委托人聊聊，免得把别人的购物清单当作机密。']]);return;}talk(c.lines,()=>{if(!state.clues.includes(o.id)){state.clues.push(o.id);save();hud();toast('记下线索：'+c.title);}});return;}
 if(o.type==='side'){const s=TALE.sides.find(x=>x.id===o.id);talk(s.lines,()=>{if(!state.sides.includes(s.id)){state.sides.push(s.id);save();toast('记下一件闲事：'+s.title);}});return;}if(o.type==='ending'){if(state.chapter<8)talk([['鹤见','公告板还空着。明天的安排要等今天的人先开口。']]);else openEndings();}}
function warp(o){mode='transition';keys.clear();path=[];pendingObject=null;waypoint=null;$('transition').hidden=false;setTimeout(()=>{state.map=o.dest;state.pos={...o.spawn};state.dir=o.back?'down':'up';state.walkFrame=1;if(!state.known.includes(o.dest))state.known.push(o.dest);trail=[];portalCooldown=performance.now()+650;mode='world';$('transition').hidden=true;hud();save();showMapName();},150);}
function nearest(){const p=state.pos;return WORLD.maps[state.map].objects.filter(o=>Math.abs(o.x-p.x)+Math.abs(o.y-p.y)<1.65).sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2-(b.x-p.x)**2-(b.y-p.y)**2)[0];}
function goTo(x,y,o=null){const m=WORLD.maps[state.map],from={x:Math.round(state.pos.x),y:Math.round(state.pos.y)};let options=o&&o.type!=='portal'?Object.values(DIRECTIONS).map(([dx,dy])=>({x:o.x+dx,y:o.y+dy})):[{x,y}];let possible=options.filter(p=>WORLD.passable(m,p.x,p.y)).map(p=>({p,path:WORLD.findPath(m,from,p)})).filter(a=>a.path.length||(a.p.x===from.x&&a.p.y===from.y)).sort((a,b)=>a.path.length-b.path.length);if(!possible.length){toast('这里走不过去。点门口或附近的路面试试。');return;}path=possible[0].path;pendingObject=o;if(!path.length&&o){pendingObject=null;interact(o);}}
function resize(){const box=canvas.getBoundingClientRect();if(!box.width)return;canvas.width=box.width<550?256:384;canvas.height=Math.round(canvas.width*box.height/box.width);ctx.imageSmoothingEnabled=false;}
function advance(dt,time){const m=WORLD.maps[state.map];if(mode!=='world'||!$('modalShade').hidden){state.walkFrame=1;return;}state.playSeconds+=dt;let dir=[...keys].at(-1),target=null;if(dir){path=[];pendingObject=null;let [dx,dy]=DIRECTIONS[dir],cx=Math.round(state.pos.x),cy=Math.round(state.pos.y);if(WORLD.passable(m,cx+dx,cy+dy))target={x:cx+dx,y:cy+dy};else if(Math.abs(state.pos.x-cx)+Math.abs(state.pos.y-cy)>.04)target={x:cx,y:cy};}else if(path.length){target=path[0];const dx=target.x-state.pos.x,dy=target.y-state.pos.y;dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');}
 let moved=false;if(target){const dx=target.x-state.pos.x,dy=target.y-state.pos.y,dist=Math.hypot(dx,dy),step=Math.min(dt*4.8,dist);if(dist>.001){state.pos.x+=dx/dist*step;state.pos.y+=dy/dist*step;state.dir=dir;state.steps+=step;walkClock+=step;state.walkFrame=Math.floor(walkClock*3.5)%4;moved=true;trail.push({x:state.pos.x,y:state.pos.y,dir:state.dir,frame:state.walkFrame});if(trail.length>120)trail.shift();}if(dist<=step+.001&&path.length)path.shift();}if(!moved)state.walkFrame=1;
 if(!path.length&&pendingObject){let o=pendingObject;pendingObject=null;interact(o);}if(mode==='world'&&time>portalCooldown){const gate=m.objects.find(o=>o.type==='portal'&&Math.abs(o.x-state.pos.x)<.19&&Math.abs(o.y-state.pos.y)<.19);if(gate){portalCooldown=time+1800;interact(gate);}}
 saveClock+=dt;if(saveClock>8){saveClock=0;save();}const near=nearest();$('nearHint').hidden=!near||mode!=='world';if(near)$('nearHint').textContent=near.type==='portal'?'A · '+near.label:near.type==='npc'?'A · 与'+TALE.people[near.person].name+'交谈':'A · 查看'+(TALE.clues[near.id]?.title||TALE.sides.find(x=>x.id===near.id)?.title||'公告板');}
function frame(time){let dt=Math.min(.04,(time-lastTime)/1000||0);lastTime=time;if(Art.ready&&mode!=='title'){advance(dt,time);const m=WORLD.maps[state.map];camera.x=Math.max(0,Math.min(m.w*16-canvas.width,(state.pos.x+.5)*16-canvas.width/2));camera.y=Math.max(0,Math.min(m.h*16-canvas.height,(state.pos.y+.5)*16-canvas.height*.55));const ids=['mio',...(state.chapter>=2?['jin']:[]),...(state.chapter>=4?['ling']:[])];const followers=ids.map((id,i)=>{let p=trail[trail.length-1-(i+1)*16];return p?{id,...p,frame:state.walkFrame===1?1:p.frame}:null;}).filter(Boolean);Art.map(ctx,m,state,camera,canvas.width,canvas.height,time,followers,waypoint);Art.minimap($('mini'),m,state);}requestAnimationFrame(frame);}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,parent=$('modalBody')){const b=el('button',text);b.onclick=fn;parent.append(b);return b;}
function paragraph(text,parent=$('modalBody'),cls){parent.append(el('p',text,cls));}
function modal(title){keys.clear();path=[];modalFocus=document.activeElement;$('modalTitle').textContent=title;$('tabs').replaceChildren();$('modalBody').replaceChildren();$('modalShade').hidden=false;$('closeModal').focus();}
function closeModal(){$('modalShade').hidden=true;if(modalFocus?.isConnected)modalFocus.focus();}
function confirmAction(title,text,fn){modal(title);paragraph(text);button('确认',fn);button('取消',closeModal);}
function readLines(title,lines){modal(title);for(const [who,text]of lines){const p=el('p',undefined,'read-line');p.append(el('b',who+'　'),document.createTextNode(text));$('modalBody').append(p);}}
function notebook(tab='clues'){modal('随身便签');for(const [id,name]of [['clues','线索'],['sides','闲事'],['people','人物'],['thoughts','思想手记'],['branches','分歧'],['maps','地图']]){const b=button(name,()=>notebook(id),$('tabs'));b.className=id===tab?'active':'';}
 const body=$('modalBody');if(tab==='clues'){paragraph('纸很轻，事情不一定。这里没有消耗道具，记下线索就够了。',body,'intro-note');for(let i=0;i<=Math.min(state.chapter,7);i++){const c=TALE.cases[i],box=el('article',undefined,'note-card');box.append(el('small','第 '+(i+1)+' 案'),el('h3',c.title));const ids=Object.keys(TALE.clues).filter(id=>TALE.clues[id].case===i&&state.clues.includes(id));if(!ids.length)paragraph('还没有记下线索。',box);for(const id of ids)button('重读 · '+TALE.clues[id].title,()=>readLines(TALE.clues[id].title,TALE.clues[id].lines),box);body.append(box);}}
 if(tab==='sides'){paragraph('这些闲事不计对错。有些会让最终的安排多出一个可能。',body,'intro-note');for(const s of TALE.sides){const found=state.sides.includes(s.id),box=el('article',undefined,'note-card'+(found?'':' locked'));box.append(el('h3',found?s.title:'还没听说的一件闲事'));if(found){button('再读一遍',()=>readLines(s.title,s.lines),box);if(s.pet){const p=el('canvas');p.width=96;p.height=104;p.style.cssText='width:96px;height:104px;image-rendering:pixelated;display:block';const im=new Image();im.onload=()=>{p.getContext('2d').drawImage(im,0,0,192,208,0,0,96,104);};im.src='assets/fanshao.webp';box.append(p);paragraph('档案里的旧吉祥物：凡少。',box);}}else paragraph('在'+WORLD.maps[s.map].name+'附近留意一下。',box,'hint');body.append(box);}}
 if(tab==='people'){const grid=el('div',undefined,'people');for(const [id,p]of Object.entries(TALE.people)){const card=el('article',undefined,'person-card'),portrait=el('canvas');Art.portrait(portrait,id);card.append(portrait,el('h3',p.name),el('small',p.job),el('p',p.bio));grid.append(card);}body.append(grid);}
 if(tab==='thoughts'){paragraph(PHILOSOPHY.intro,body,'intro-note');paragraph('每办完一案，四组阅读札记会在这里展开。故事中的 AI 情境是当代延伸；照料某个存在者，并不能倒推出它已被证明是此在。',body,'hint');for(let i=0;i<8;i++){body.append(el('h3','第 '+(i+1)+' 案 · '+TALE.cases[i].chapterName));if(i>=state.chapter){paragraph('调查完成后再回来看。读手记不是通关条件。',body,'hint');continue;}for(const c of PHILOSOPHY.chapters[i].cards){const d=el('details',undefined,'concept'),s=el('summary',c.term);s.append(el('small',c.de));d.append(s);paragraph(c.scene,d);paragraph(c.meaning,d);paragraph('别急着这样理解：'+c.misread,d);paragraph('继续想一想：'+c.question,d);paragraph('阅读位置：'+c.ref,d,'source');const source=PHILOSOPHY.sources.find(x=>x.id===c.source);if(source){let a=el('a',source.name+' ↗');a.href=source.url;a.target='_blank';a.rel='noopener';d.append(a);}body.append(d);}}const a=el('a','阅读完整思想手记（含后续情境） ↗');a.href='notes.html';a.target='_blank';a.rel='noopener';body.append(a);}
 if(tab==='branches'){paragraph('每案有两条调查路线、三种处置。回溯会撤回此节点之后的线索和选择；已看过的结局仍保留。没有“本真分数”。',body,'intro-note');for(let i=0;i<8;i++){const c=TALE.cases[i],r=state.records[i],box=el('article',undefined,'note-card'+(i>state.chapter?' locked':''));box.append(el('h3','0'+(i+1)+' · '+c.title));if(i<=state.chapter){for(const [list,pick]of [[c.routes,r.route],[c.decisions,r.decision]]){const tree=el('div',undefined,'choice-tree');list.forEach((o,n)=>tree.append(el('span',o.label,pick===n?'chosen':'')));box.append(tree);}if(r.completed)paragraph(c.decisions[r.decision].after,box,'choice-record');state.checkpoints.forEach((p,n)=>{if(p.chapter===i)button('回到'+(p.kind==='route'?'调查路线':'处置决定'),()=>confirmAction('翻回这一页？','此节点后的调查与选择会撤回。若想保留当前路线，可以先在存档页导出。',()=>rewind(n)),box);});}body.append(box);}body.append(el('h3','已见结局 · '+state.endings.length+' / '+TALE.endings.length));for(const e of TALE.endings)if(state.endings.includes(e.id))button(e.name,()=>readLines(e.name,e.lines));}
 if(tab==='maps'){const box=el('div',undefined,'world-chart'),chart=el('canvas');Art.minimap(chart,WORLD.maps.isles,{...state,pos:state.map==='isles'?state.pos:{x:-10,y:-10}});box.append(chart);body.append(box);paragraph('白页群岛 → 城镇 / 城堡 → 房间 → 暗道。选一个已经去过的地点，可查看走法；需要亲自走到门口。',body,'intro-note');const grid=el('div',undefined,'map-links');for(const id of state.known){let b=button(WORLD.maps[id].name,()=>routeHint({map:id,...WORLD.maps[id].start,text:'前往'+WORLD.maps[id].name}),grid);b.append(el('small',WORLD.ancestors(id).slice(0,-1).join(' › ')||'大地图'));}body.append(grid);}}
function routeHint(goal=objective()){const routes=WORLD.mapRoute(state.map,goal.map,state);modal('路在这里');paragraph(goal.text);if(routes===null){paragraph('先选定本案的调查路线，或完成眼前这件事。');return;}const current=routes.length?routes[0]:goal;paragraph(routes.length?WORLD.maps[state.map].name+' → '+routes.map(o=>WORLD.maps[o.dest].name).join(' → '):'就在'+WORLD.maps[state.map].name+'，留意闪光或头顶的记号。');paragraph('金色方框只标记下一步。到下一张地图后，可以再来问路。',$('modalBody'),'hint');button('在地图上标出来',()=>{waypoint={map:state.map,x:current.x,y:current.y};closeModal();});button('走向附近的入口 / 线索',()=>{waypoint={map:state.map,x:current.x,y:current.y};closeModal();const o=WORLD.maps[state.map].objects.find(x=>x.x===current.x&&x.y===current.y);goTo(current.x,current.y,o);});}
function openEndings(){modal('明天，怎么过？');paragraph('过去的安排决定今天哪些方案做得起来。它们各有代价，都不能替 AI 是否具有此在给出终局证明。');for(const e of TALE.endings){const allowed=endingAllowed(e),box=el('article',undefined,'ending-option');box.append(el('h3',e.name));paragraph(e.subtitle,box);paragraph(allowed?'可以提出这个方案':e.need,box,'hint');const b=button(allowed?e.choice:'尚未具备条件',()=>{closeModal();talk(e.lines,()=>{if(!state.endings.includes(e.id))state.endings.push(e.id);save();const finish=()=>{modal('明天照常营业');const t=el('div',undefined,'ending-title');t.append(el('small','已抵达一种结局'),el('h3',e.name),el('p',e.subtitle));$('modalBody').append(t);paragraph('还可以继续走走、回看分歧，或在公告板前商量别的安排。');button('继续探索',closeModal);button('回看分歧',()=>notebook('branches'));};if(state.sides.length===8)talk(TALE.extra,finish);else finish();});},box);b.disabled=!allowed;$('modalBody').append(box);}}
function help(){modal('第一次来？');paragraph('你是跑腿员凡少。先到方糖镇早餐铺找绫婆，商量调查路线，再查看三条线索，回去作一个决定。八个案件会带你穿过城镇、房间与地下暗道。');for(const [a,b]of [['走路','方向键 / WASD，或点地面'],['交谈 / 查看','E / 空格 / A 按钮，或点人物与闪光'],['进门','走到门口，或点建筑'],['看地图','M；小地图金点是入口，白点是你'],['便签与分歧','J / Y；回溯可重选，后续记录会撤回'],['手机','点地面，也可按住下方方向键']]){const row=el('div',undefined,'keyboard-row');row.append(el('span',a),el('span',b));$('modalBody').append(row);}paragraph('没有战斗，没有倒计时，没有答错惩罚。手记可以稍后再读。存档自动保存在当前浏览器；换设备用导出 / 导入。',$('modalBody'),'hint');}
function savePanel(){modal('把今天夹进书里');paragraph('自动存档属于当前浏览器。换手机、换电脑或清理浏览器前，请先导出。旧版冒险的存档没有被覆盖。');const row=el('div',undefined,'save-actions');if(mode!=='title')button('导出当前存档',()=>{save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='明天照常营业-第'+(Math.min(state.chapter,7)+1)+'案.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出存档。');},row);button('导入存档',()=>$('importFile').click(),row);if(mode!=='title')button('重新开始',()=>confirmAction('重新开始？','会替换当前新版存档。想保留这一条路线，请先导出。',()=>{start(fresh());save();talk(TALE.opening);}),row);$('modalBody').append(row);}
$('importFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>800000)throw Error('存档文件过大。');const s=cleanSave(JSON.parse(await f.text()));confirmAction('导入这份存档？','将恢复到第 '+Math.min(s.chapter+1,8)+' 案 · '+WORLD.maps[s.map].name+'，替换当前新版自动存档。',()=>{start(s);save();toast('存档已恢复。');});}catch(err){toast('无法导入：'+err.message);}};
$('newGame').onclick=()=>{const run=()=>{start(fresh());save();talk(TALE.opening);};if(!$('continueGame').hidden)confirmAction('开始新的今天？','当前自动存档会被替换。可以取消后先导出。',run);else run();};$('continueGame').onclick=()=>{try{start(cleanSave(JSON.parse(localStorage.getItem(SAVE))));}catch(e){toast(e.message);}};
$('nextLine').onclick=next;$('readSegment').onclick=()=>{if(dialog){dialog.at=dialog.lines.length-1;renderLine();}};$('actionBtn').onclick=()=>mode==='dialogue'?next():interact(nearest());$('hintBtn').onclick=()=>routeHint();for(const id of ['notesTop','notesBtn'])$(id).onclick=()=>notebook();$('mapBtn').onclick=()=>notebook('maps');$('branchesBtn').onclick=()=>notebook('branches');for(const id of ['helpBtn','titleGuide'])$(id).onclick=help;for(const id of ['saveBtn','titleSave'])$(id).onclick=savePanel;$('closeModal').onclick=closeModal;$('modalShade').onclick=e=>{if(e.target===$('modalShade'))closeModal();};
canvas.addEventListener('pointerdown',e=>{if(mode!=='world'||!$('modalShade').hidden)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*canvas.width/rect.width+camera.x,y=(e.clientY-rect.top)*canvas.height/rect.height+camera.y;const m=WORLD.maps[state.map],scale=m.kind==='overworld'?.58:1;const hit=m.objects.filter(o=>{let footX=(o.x+.5)*16,footY=(o.y+1)*16;let w=o.type==='portal'&&!o.back?(Art.propFrames[o.art]?.w||16)*scale:20,h=o.type==='portal'&&!o.back?(Art.propFrames[o.art]?.h||16)*scale:28;return Math.abs(x-footX)<=w/2&&y<=footY+4&&y>=footY-h;}).sort((a,b)=>b.y-a.y)[0];if(hit)goTo(hit.x,hit.y,hit);else goTo(Math.floor(x/16),Math.floor(y/16));canvas.focus({preventScroll:true});});
const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};
window.addEventListener('keydown',e=>{if(!$('modalShade').hidden){if(e.key==='Escape')closeModal();if(e.key==='Tab'){const all=[...$('modal').querySelectorAll('button:not(:disabled),a[href],summary,input')].filter(x=>!x.hidden),first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}return;}if(mode==='title')return;if(mode==='dialogue'){if(['Enter',' ','e','E'].includes(e.key)&&document.activeElement.tagName!=='BUTTON'){e.preventDefault();if(!e.repeat)next();}return;}if(keyMap[e.key]){e.preventDefault();keys.add(keyMap[e.key]);}else if([' ','e','E'].includes(e.key)){e.preventDefault();if(!e.repeat)interact(nearest());}else if(e.key.toLowerCase()==='m')notebook('maps');else if(e.key.toLowerCase()==='j')notebook();else if(e.key.toLowerCase()==='y')notebook('branches');});window.addEventListener('keyup',e=>keys.delete(keyMap[e.key]));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();if(mode!=='title')save();});
for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=e=>{e.preventDefault();if(mode==='world')keys.add(b.dataset.dir);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>keys.delete(b.dataset.dir);}
$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('当前浏览器不支持全屏，可以横屏游玩。');}};
$('sound').onclick=async()=>{try{audioContext||=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();soundOn=!soundOn;$('sound').querySelector('span').textContent=soundOn?'声音开':'声音关';$('sound').setAttribute('aria-label',soundOn?'关闭声音':'打开声音');if(soundOn){const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=523.25;gain.gain.setValueAtTime(.045,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.35);oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.4);}}catch{toast('这个浏览器暂时无法打开声音。');}};
setInterval(()=>{if(!soundOn||mode==='title'||document.hidden)return;const t=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.type='triangle';o.frequency.value=[261.63,329.63,392,440][Math.floor(state.steps)%4];g.gain.setValueAtTime(.008,t);g.gain.exponentialRampToValueAtTime(.0001,t+1.1);o.connect(g).connect(audioContext.destination);o.start(t);o.stop(t+1.2);},2200);
window.addEventListener('resize',resize);new ResizeObserver(resize).observe($('stage'));updateContinue();Art.init().then(()=>{$('newGame').disabled=false;$('continueGame').disabled=false;$('newGame').textContent='开始今天的调查';$('loadMessage').textContent='八个日常悬案 · 六种结局 · 随时自动保存';}).catch(e=>{$('loadMessage').textContent=e.message+'。请刷新页面重试。';});requestAnimationFrame(frame);
const inspect=()=>({title:TALE.title,mode,chapter:state.chapter+1,map:state.map,mapName:WORLD.maps[state.map].name,position:{...state.pos},direction:state.dir,walkFrame:state.walkFrame,goal:objective().text,clues:[...state.clues],sides:[...state.sides],records:clone(state.records),endings:[...state.endings],dialogue:dialog?{speaker:dialog.lines[dialog.at][0],text:$('dialogueText').textContent,choices:[...$('choices').children].map(x=>x.textContent)}:null,near:nearest()?.id||null});
window.Tomorrow=Object.freeze({inspect});if(navigator.modelContext?.registerTool)try{navigator.modelContext.registerTool({name:'read_tomorrow_game',description:'Read the current mystery game scene, position, notebook and visible choices. Read only.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify(inspect())}]})});}catch{}
})();
