'use strict';
(() => {
const $=id=>document.getElementById(id), canvas=$('world'), ctx=canvas.getContext('2d');
const SAVE='ash-names-save-v1', VERSION=2, TILE=16, MW=44, MH=28;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const sleep=ms=>new Promise(r=>setTimeout(r,reducedMotion?Math.min(ms,130):ms));
let reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state=null, mode='title', map=null, camera={x:0,y:0}, keys={}, path=[], near=null, moving=false;
let W=480,H=288,lastTime=0,lastSaved=0,lastHint='',dialogue=null,battle=null,fx=null,activeModal='',focusBeforeModal=null;
let toastTimer,locationTimer,bannerTimer,actionLock=false;
const sprite=new Image(),landscape=new Image();sprite.src='assets/fanshao.webp';landscape.src='assets/shattered-sun.png';
let spriteReady=false;const portraits=[];
sprite.onload=()=>{spriteReady=true;for(let i=0;i<3;i++){let c=document.createElement('canvas');c.width=32;c.height=40;let g=c.getContext('2d');g.imageSmoothingEnabled=false;if(i===1)g.filter='hue-rotate(145deg) saturate(.65)';if(i===2)g.filter='hue-rotate(230deg) brightness(.8)';g.drawImage(sprite,0,0,192,208,0,-1,32,40);portraits[i]=c.toDataURL();}if(atlasCells?.chars?.length){for(let i=0;i<3;i++){let c=document.createElement('canvas');c.width=c.height=96;drawFace(c.getContext('2d'),i,96);portraits[i]=c.toDataURL();}}if(state)renderHUD();};

const tileArt=new Image(),propArt=new Image(),charArt=new Image();
const atlasCells={props:[],chars:[]},NPC_LOOKS=[[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[1,14,0]],BOSS_LOOKS=[25,26,27,28,17,29,30,31];
const FACE_NAMES={'凡少':0,'澪':1,'烬':2,'竹翁':4,'绫婆':5,'小满':6,'鹿九':7,'鸣砂':8,'舟生':9,'白驿':10,'阿眠':11,'点点':12,'栖川':13,'铃':14,'春姨':15,'乌纸':16,'鹤见':17,'金叔':18,'闻灯':19,'七':20,'桐':21,'一页':22,'旧凡少':23,'旧世界的凡少':23,'未来的凡少':23,'阿朔':24,'无面守桥人':25,'千声井母':26,'白面追猎者':27,'潮汐巨像':28,'第一日轮':29,'七十七重影':30,'神谕':31,'记名人':0,'代理书记':20,'门槛':20,'孩子':6};
function prepareAtlas(img,cols,rows,key){
 const c=document.createElement('canvas'),g=c.getContext('2d',{willReadFrequently:true});
 for(let r=0;r<rows;r++)for(let col=0;col<cols;col++){
  const sx=Math.round(col*img.naturalWidth/cols),sy=Math.round(r*img.naturalHeight/rows),sw=Math.round((col+1)*img.naturalWidth/cols)-sx,sh=Math.round((r+1)*img.naturalHeight/rows)-sy;c.width=sw;c.height=sh;g.clearRect(0,0,sw,sh);g.drawImage(img,sx,sy,sw,sh,0,0,sw,sh);
  const data=g.getImageData(0,0,sw,sh).data;let left=sw,top=sh,right=0,bottom=0;
  for(let y=0;y<sh;y++)for(let x=0;x<sw;x++)if(data[(y*sw+x)*4+3]>130){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}
  atlasCells[key].push({sx:sx+left,sy:sy+top,sw:right-left+1,sh:bottom-top+1});
 }
 if(key==='chars'){for(let i=0;i<3;i++){const c=document.createElement('canvas');c.width=c.height=96;drawFace(c.getContext('2d'),i,96);portraits[i]=c.toDataURL();}if(state)renderHUD();if(dialogue)renderFace(dialogue.lines[dialogue.index][0]);}
 if(map)map.base=null;
}
function drawAtlas(g,key,index,x,y,w,h,alpha=1){const a=atlasCells[key][index],img=key==='chars'?charArt:propArt;if(!a)return false;g.save();g.globalAlpha=alpha;g.imageSmoothingEnabled=false;g.drawImage(img,a.sx,a.sy,a.sw,a.sh,x,y,w,h);g.restore();return true;}
function drawFace(g,index,size){const a=atlasCells.chars[index];g.clearRect(0,0,size,size);g.fillStyle=['#394c51','#30444e','#433950','#474433'][index%4];g.fillRect(0,0,size,size);if(!a)return;const sw=a.sw*.78,sh=Math.min(a.sh*.5,sw),sx=a.sx+(a.sw-sw)/2,sy=a.sy+a.sh*.045;g.imageSmoothingEnabled=false;g.drawImage(charArt,sx,sy,sw,sh,0,0,size,size);}
function renderFace(speaker){if(speaker==='门槛'||speaker==='代理书记'){const el=$('dialoguePortrait');el.hidden=false;$('dialogue').classList.add('with-face');let g=el.getContext('2d');g.fillStyle='#163848';g.fillRect(0,0,128,128);g.strokeStyle='#90deea';g.lineWidth=3;g.beginPath();for(let x=10;x<118;x++){let y=64+Math.sin(x*.18)*(speaker==='门槛'?17:8);if(x===10)g.moveTo(x,y);else g.lineTo(x,y);}g.stroke();g.fillStyle='#b3dce5';g.font='11px monospace';g.fillText(speaker==='门槛'?'THRESHOLD':'CIVIC AGENT',18,108);return;}let id=FACE_NAMES[speaker];if(id===undefined){const found=Object.keys(FACE_NAMES).find(n=>speaker.endsWith(n)&&n.length>1);if(found)id=FACE_NAMES[found];}const el=$('dialoguePortrait');el.hidden=id===undefined||!atlasCells.chars.length;$('dialogue').classList.toggle('with-face',!el.hidden);if(!el.hidden)drawFace(el.getContext('2d'),id,128);}
function texture(g,index,x,y,w,h){if(!tileArt.complete||!tileArt.naturalWidth)return false;const col=index%4,row=Math.floor(index/4),sw=tileArt.naturalWidth/4,sh=tileArt.naturalHeight/4;g.imageSmoothingEnabled=false;const ox=((Math.round(x/16)%2)+2)%2,oy=((Math.round(y/16)%2)+2)%2;g.drawImage(tileArt,Math.round(col*sw+ox*sw/2),Math.round(row*sh+oy*sh/2),Math.floor(sw/2),Math.floor(sh/2),x,y,w,h);return true;}
propArt.onload=()=>prepareAtlas(propArt,4,4,'props');charArt.onload=()=>prepareAtlas(charArt,4,8,'chars');tileArt.onload=()=>{if(map)map.base=null;};
tileArt.src='assets/terrain.png';propArt.src='assets/props.png';charArt.src='assets/characters.png';
const SKILLS=[
 [{id:'echo',name:'回响星弧',lv:1,cost:6,power:1.8,fx:'arc',desc:'星光汇聚 · 单体魔法'},
  {id:'mirrors',name:'镜影连奏',lv:3,cost:10,power:.94,hits:3,fx:'clone',desc:'幻影交错 · 连续三击'},
  {id:'fall',name:'星屑坠落',lv:6,cost:14,power:1.8,all:true,fx:'meteor',desc:'星屑雨 · 全体魔法'},
  {id:'sky',name:'天穹回响',lv:11,cost:20,power:3,all:true,fx:'nova',desc:'法阵展开 · 全体重创'}],
 [{id:'heal',name:'记忆之泉',lv:1,cost:8,heal:true,fx:'heal',desc:'全队回复生命'},
  {id:'barrier',name:'月镜守护',lv:4,cost:10,shield:true,fx:'shield',desc:'全队下次受击减伤 65%'},
  {id:'needles',name:'碎镜星雨',lv:7,cost:12,power:2,all:true,fx:'shards',desc:'镜片落下 · 全体魔法'},
  {id:'revive',name:'逆时回声',lv:12,cost:22,revive:true,fx:'heal',desc:'复苏倒下的同伴并全队治疗'}],
 [{id:'blade',name:'铭光之刃',lv:1,cost:7,power:2,fx:'slash',desc:'魔力附刃 · 单体剑技'},
  {id:'crescent',name:'弦月斩',lv:4,cost:10,power:2.8,fx:'slash',desc:'剑光成弧 · 单体重创'},
  {id:'nightfall',name:'长夜挽歌',lv:8,cost:16,power:2.4,all:true,fx:'nova',desc:'领域展开 · 全体剑技'},
  {id:'oath',name:'断誓双生',lv:13,cost:20,power:2.1,hits:2,fx:'clone',desc:'穿越重影 · 两次重斩'}]
];
const THEMES={
 village:{grass:'#274e46',grass2:'#305b4c',path:'#927e5a',edge:'#192f34',water:'#234e60',leaf:'#265451',leaf2:'#397764',roof:'#8e5b48',flower:'#e5b983'},
 water:{grass:'#345a61',grass2:'#3f7070',path:'#9a9679',edge:'#183f51',water:'#24536b',leaf:'#35555e',leaf2:'#53827f',roof:'#676e8b',flower:'#c0d7c5'},
 forest:{grass:'#214a44',grass2:'#2b6050',path:'#737556',edge:'#142f32',water:'#244c55',leaf:'#18463d',leaf2:'#367257',roof:'#43554a',flower:'#9baece'},
 city:{grass:'#475960',grass2:'#54696b',path:'#8b8980',edge:'#293e4d',water:'#315c70',leaf:'#3a4f4c',leaf2:'#6a7b60',roof:'#76566d',flower:'#dfbd90'},
 snow:{grass:'#9daebe',grass2:'#b9c6cb',path:'#7b94a6',edge:'#4a627a',water:'#567d99',leaf:'#667f94',leaf2:'#c5d5d7',roof:'#6b7386',flower:'#f1dfc3'},
 ruins:{grass:'#44465b',grass2:'#57536a',path:'#807183',edge:'#28283e',water:'#463d6b',leaf:'#3c3850',leaf2:'#685575',roof:'#5f475c',flower:'#d3a1c2'},
 core:{grass:'#302d4d',grass2:'#3b3759',path:'#796676',edge:'#171b33',water:'#66425f',leaf:'#30354f',leaf2:'#766b85',roof:'#755772',flower:'#ecc48e'}
};
const Audio={ctx:null,on:false,timer:null,index:0,
 init(){if(!this.ctx){const A=window.AudioContext||window.webkitAudioContext;if(A)this.ctx=new A();}if(this.ctx?.state==='suspended')this.ctx.resume().catch(()=>{});},
 tone(freq=440,duration=.1,type='triangle',volume=.04){if(!this.on||!this.ctx)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+duration+.02);},
 toggle(){this.init();this.on=!this.on;if(this.on){this.index=0;this.timer=setInterval(()=>this.music(),330);}else clearInterval(this.timer);$('soundBtn').innerHTML=this.on?'♫ <span>声音开</span>':'♫ <span>声音关</span>';$('soundBtn').setAttribute('aria-label',this.on?'关闭声音':'打开声音');},
 music(){if(document.hidden||!this.on)return;const notes=mode==='battle'?[220,293.66,329.63,440,415.3,329.63,293.66,246.94]:[196,293.66,329.63,392,440,392,329.63,293.66,220,329.63,392,440,493.88,440,392,329.63];this.tone(notes[this.index%notes.length],.32,'triangle',.018);if(this.index%4===0)this.tone(notes[this.index%notes.length]/2,.6,'sine',.025);this.index++;},
 effect(kind){if(kind==='heal'){[392,493,587].forEach((n,i)=>setTimeout(()=>this.tone(n,.25,'sine',.055),i*90));}else if(kind==='nova'||kind==='shards'){[110,880,220,660].forEach((n,i)=>setTimeout(()=>this.tone(n,.15,'sawtooth',.025),i*50));}else if(kind==='win'){[261,329,392,523].forEach((n,i)=>setTimeout(()=>this.tone(n,.28,'triangle',.05),i*100));}else{this.tone(210,.12,'square',.023);setTimeout(()=>this.tone(420,.16,'triangle',.05),90);}}
};
function blankProgress(){return {reflected:false,inquiryChoices:[],guide:false,witness:false,relic:false,side:false,kills:0,boss:false,resolved:false,choice:null,cleared:[]};}
function newState(){return {version:VERSION,chapter:0,unlocked:0,level:1,xp:0,gold:40,potions:5,ethers:3,limit:0,heroes:[{hp:0,mp:0},{hp:0,mp:0},{hp:0,mp:0}],progress:STORY.chapters.map(blankProgress),pos:{x:6,y:16},endings:[],playSeconds:0,started:Date.now(),updated:Date.now()};}
const ch=()=>STORY.chapters[state.chapter], prog=()=>state.progress[state.chapter];
function partySize(){return state.unlocked>=1?3:2;}
function stats(i){let l=state.level,atk=[12,9,14][i]+l*3,def=[4,4,3][i]+l*1.25,hp=[91,78,86][i]+l*14,mp=[25,35,23][i]+l*3;state.progress.forEach((p,k)=>{if(p.relic){let r=STORY.chapters[k].relic;if(r.stat==='atk')atk+=r.value;if(r.stat==='def')def+=r.value;if(r.stat==='hp')hp+=r.value;if(r.stat==='mp')mp+=r.value;}});return {atk:Math.floor(atk),def:Math.floor(def),hp,mp};}
function healParty(){state.heroes.forEach((h,i)=>{const s=stats(i);h.hp=s.hp;h.mp=s.mp;});}
function xpNext(){return 30+state.level*15;}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3600);}
function save(){if(!state)return false;state.updated=Date.now();try{localStorage.setItem(SAVE,JSON.stringify(state));$('saveStatus').textContent='● 进度已自动保存';$('saveNote').textContent='已存档 · 当前浏览器';lastSaved=performance.now();return true;}catch{ $('saveStatus').textContent='存档空间不可用';$('saveNote').textContent='自动存档不可用，请导出存档';return false;}}
function validateSave(s){
 if(!s||typeof s!=='object'||![1,VERSION].includes(s.version))throw Error('存档版本不兼容');
 const num=(n,a,b)=>Number.isFinite(n)&&n>=a&&n<=b;
 if(!Number.isInteger(s.chapter)||!num(s.chapter,0,7)||!Number.isInteger(s.unlocked)||!num(s.unlocked,s.chapter,7)||!Number.isInteger(s.level)||!num(s.level,1,30)||!num(s.xp,0,100000)||!num(s.gold,0,10000000)||!num(s.potions,0,999)||!num(s.ethers,0,999)||!num(s.limit,0,100))throw Error('存档数值无效');
 if(!Array.isArray(s.heroes)||s.heroes.length!==3||s.heroes.some(h=>!h||!num(h.hp,0,10000)||!num(h.mp,0,10000)))throw Error('伙伴数据无效');
 if(!Array.isArray(s.progress)||s.progress.length!==8)throw Error('章节数据不完整');
 for(let [chapterIndex,p] of s.progress.entries()){if(!p||['guide','witness','relic','side','boss','resolved'].some(k=>typeof p[k]!=='boolean')||!num(p.kills,0,9999)||![null,'a','b'].includes(p.choice)||!Array.isArray(p.cleared)||p.cleared.some(v=>!Number.isInteger(v)||v<0||v>3))throw Error('剧情数据无效');if(p.reflected===true&&(!Array.isArray(p.inquiryChoices)||p.inquiryChoices.length!==2||!Number.isInteger(p.inquiryChoices[0])||!Number.isInteger(p.inquiryChoices[1])||p.inquiryChoices[0]<0||p.inquiryChoices[0]>=AI_CASES[chapterIndex].first.options.length||p.inquiryChoices[1]<0||p.inquiryChoices[1]>=AI_CASES[chapterIndex].second.options.length))throw Error('追问记录无效');}
 if(!s.pos||!num(s.pos.x,0,MW-1)||!num(s.pos.y,0,MH-1)||!Array.isArray(s.endings)||s.endings.some(k=>!Object.hasOwn(STORY.endings,k))||!num(s.playSeconds,0,100000000))throw Error('存档结构无效');
 const clean=newState();for(let k of ['chapter','unlocked','level','xp','gold','potions','ethers','limit','playSeconds'])clean[k]=s[k];clean.heroes=s.heroes.map(h=>({hp:h.hp,mp:h.mp}));clean.progress=s.progress.map(p=>({reflected:p.reflected===true,inquiryChoices:Array.isArray(p.inquiryChoices)?p.inquiryChoices.filter(v=>Number.isInteger(v)&&v>=0&&v<3).slice(0,2):[],guide:p.guide,witness:p.witness,relic:p.relic,side:p.side,kills:p.kills,boss:p.boss,resolved:p.resolved,choice:p.choice,cleared:[...new Set(p.cleared)]}));clean.pos={x:s.pos.x,y:s.pos.y};clean.endings=[...new Set(s.endings)];return clean;
}
function loadStored(){try{let raw=localStorage.getItem(SAVE);return raw?validateSave(JSON.parse(raw)):null;}catch{return null;}}
function showTitle(){mode='title';$('titleScreen').hidden=false;$('playScreen').hidden=true;const saved=loadStored();$('continueBtn').hidden=!saved;if(saved){$('continueBtn').innerHTML='继续旅程 · 第 '+(saved.chapter+1)+' 章 <span>→</span>';$('titleChapter').textContent=STORY.chapters[saved.chapter].place;}}
function startGame(s,isNew=false){state=s;dialogue=null;battle=null;fx=null;path=[];keys={};closeModal();$('titleScreen').hidden=true;$('playScreen').hidden=false;mode='world';if(isNew)healParty();enterMap(false);resizeCanvas();renderHUD();save();if(isNew)showDialogue(ch().intro,()=>{save();toast('先找黄色叹号旁的守钟人。靠近按 E / A。');});else toast('旅程已继续 · '+ch().place);}
function enterMap(resetPos=true){map=createMap(state.chapter);if(resetPos)state.pos={...map.start};if(!walkable(Math.round(state.pos.x),Math.round(state.pos.y))||state.heroes.slice(0,partySize()).every(h=>h.hp<=0)){state.pos={...map.start};healParty();}path=[];mode='world';battle=null;fx=null;near=null;lastHint=null;$('interactHint').hidden=true;$('interactHint').textContent='';$('battleUI').hidden=true;$('fieldBar').hidden=false;$('touchControls').hidden=false;camera={x:0,y:0};location(ch().place);renderHUD();}
function location(name){$('locationToast').textContent=name;$('locationToast').hidden=false;clearTimeout(locationTimer);locationTimer=setTimeout(()=>$('locationToast').hidden=true,2200);}
function createMap(index){
 const data=STORY.chapters[index],theme=THEMES[data.theme],seed=(x,y)=>{let n=Math.sin(x*127.1+y*311.7+index*87.33)*43758.5453;return n-Math.floor(n);};
 let tiles=Array.from({length:MH},(_,y)=>Array.from({length:MW},(_,x)=>{if(x<2||y<2||x>MW-3||y>MH-3)return 3;const river=20+Math.round(Math.sin(y*.27+index)*2);if(x>=river&&x<river+3)return 2;let r=seed(x,y);if(r>.92)return 3;return 0;}));
 const shift=index%3-1;
 const objs=[{type:'guide',x:11,y:13+shift,name:data.npcs[0]},{type:'witness',x:14,y:7+shift,name:data.npcs[1]},{type:'side',x:5,y:6,name:data.npcs[2]},{type:'shop',x:5,y:21,name:'行商 · 药与旅途'},{type:'camp',x:10,y:20,name:'营火 · 回复生命与魔力'},{type:'chest',x:31,y:6+shift,name:data.relic.name},{type:'boss',x:37,y:13+shift,name:data.boss},{type:'gate',x:39,y:22,name:data.exit},{type:'inquiry',x:18,y:20,name:AI_CASES[index].object},{type:'sign',x:12,y:17,name:'路标与地图'}];
 const mobs=[{type:'enemy',id:0,x:27,y:16,name:data.enemy[0]},{type:'enemy',id:1,x:32,y:21,name:data.enemy[1]},{type:'enemy',id:2,x:29,y:10,name:data.enemy[0]},{type:'enemy',id:3,x:36,y:18,name:data.enemy[1]}];
 const brush=(x,y,w=0)=>{for(let a=-w;a<=w;a++)for(let b=-w;b<=w;b++){let yy=y+b,xx=x+a;if(xx>1&&yy>1&&xx<MW-2&&yy<MH-2)tiles[yy][xx]=tiles[yy][xx]===2?4:1;}};
 const road=(ax,ay,bx,by)=>{let x=ax,y=ay;brush(x,y);while(x!==bx){x+=Math.sign(bx-x);brush(x,y);}while(y!==by){y+=Math.sign(by-y);brush(x,y);}};
 road(6,16,39,16);road(8,6,8,22);road(29,6,29,23);road(14,7+shift,31,7+shift);
 for(let o of [...objs,...mobs])road(o.x,o.y,o.x<20?8:29,16);
 brush(9,16,1);brush(14,8,1);brush(30,7,1);
 const buildings=[{x:5,y:10,w:5,h:3},{x:12,y:4,w:5,h:2},{x:5,y:23,w:5,h:2}];
 for(let b of buildings)for(let y=b.y;y<b.y+b.h;y++)for(let x=b.x;x<b.x+b.w;x++)if(!objs.some(o=>o.x===x&&o.y===y))tiles[y][x]=5;
 return {tiles,objects:objs,mobs,buildings,theme,seed,start:{x:6,y:16}};
}
function walkable(x,y){return map&&x>=0&&y>=0&&x<MW&&y<MH&&[0,1,4].includes(map.tiles[y][x]);}
function entities(){return [...map.objects.filter(o=>!(o.type==='boss'&&prog().boss)),...map.mobs.filter(o=>!prog().cleared.includes(o.id))];}
function findPath(tx,ty){tx=clamp(Math.round(tx),2,MW-3);ty=clamp(Math.round(ty),2,MH-3);if(!walkable(tx,ty))return [];const sx=Math.round(state.pos.x),sy=Math.round(state.pos.y),queue=[[sx,sy]],visited=new Map([[`${sx},${sy}`,null]]);let cursor=0;while(cursor<queue.length){const [x,y]=queue[cursor++];if(x===tx&&y===ty){let p=[],k=`${tx},${ty}`;while(visited.get(k)!==null){const [px,py]=k.split(',').map(Number);p.unshift({x:px,y:py});k=visited.get(k);}return p;}for(let [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy,k=`${nx},${ny}`;if(walkable(nx,ny)&&!visited.has(k)){visited.set(k,`${x},${y}`);queue.push([nx,ny]);}}}return [];}
function targetObject(o){if(mode!=='world'||!$('modalShade').hidden)return;if(Math.hypot(o.x-state.pos.x,o.y-state.pos.y)<1.9){interact(o);return;}path=findPath(o.x,o.y);path.target=o;}
function objectiveLabel(o){if(o.type==='guide')return prog().guide?'交谈':'调查';if(o.type==='witness')return prog().witness?'交谈':'调查';if(o.type==='side')return prog().side?'交谈':'留下见证';if(o.type==='chest')return prog().relic?'查看':'打开';if(o.type==='enemy'||o.type==='boss')return '战斗';if(o.type==='gate')return '前进';if(o.type==='inquiry')return '追问';return '互动';}
function interact(o=near){if(mode==='dialogue'){advanceDialogue();return;}if(mode!=='world'||!$('modalShade').hidden)return;if(!o){toast('走近人物、营火、宝箱或路标，再按互动。');return;}path=[];keys={};const p=prog(),c=ch();
 if(o.type==='guide'){if(p.guide){showDialogue([[c.npcs[0],p.boss?'路已经打开了。也可以回头找找还没听完的故事。':c.objective]]);return;}showDialogue(c.guide,()=>{p.guide=true;renderHUD();save();toast('线索已更新 · 寻找 '+c.npcs[1]);});}
 if(o.type==='witness'){if(!p.guide){showDialogue([[c.npcs[1],'先去找 '+c.npcs[0]+'。把眼前的事情弄清楚，我们再继续。']]);return;}if(p.witness){showDialogue([[c.npcs[1],c.lore]]);return;}showDialogue(c.witness,()=>{p.witness=true;renderHUD();save();toast('祭坛封印已解除 · 可以取回 '+c.relic.name);});}
 if(o.type==='side'){if(p.side){showDialogue([[c.npcs[2],'谢谢你替我留住那个故事。你要走的时候，不用答应一定会回来。平安就好。']]);return;}showDialogue(c.side,()=>{p.side=true;state.gold+=25;renderHUD();save();Audio.effect('heal');toast('记忆残页 +1 · '+c.memory+' ｜ 铜钱 +25');});}
 if(o.type==='chest'){if(p.relic){toast('已经获得 '+c.relic.name);return;}if(!p.witness){showDialogue([['封印的祭坛','需要先听完两位主线人物的证词，才能解开宝物封印。']]);return;}showDialogue([['旁白','你打开祭坛中央的宝匣。'+c.relic.desc],['凡少','「'+c.relic.name+'」……这一次，我们把它带走。']],()=>{p.relic=true;healParty();renderHUD();save();Audio.effect('win');toast('宝物解锁 · '+c.relic.name+' ｜ 全队已恢复');});}
 if(o.type==='camp')rest();
 if(o.type==='shop')openShop();
 if(o.type==='sign')openJournal('map');if(o.type==='inquiry'){if(!p.witness){showDialogue([['回响终端','先听取本章两名主线人物的证词，再回来共同追问。']]);return;}runInquiry();}
 if(o.type==='enemy')startBattle(false,o.id);
 if(o.type==='boss'){if(!p.guide||!p.witness||!p.relic||!p.reflected||p.kills<2){showDialogue([['前方的封印','首领受到旧日轮保护。先完成两段调查、拿到宝物、完成本章追问，并击败至少两组普通敌人。当前讨伐：'+Math.min(2,p.kills)+'/2。']]);return;}showDialogue(c.before,()=>startBattle(true));}
 if(o.type==='gate'){if(!p.boss){toast('本章首领尚未击败，前路仍被封锁。');return;}if(!p.resolved){finishChapterStory();return;}if(state.chapter===7)chooseEnding();else travel(state.chapter+1,true);}
}
function rest(){if(mode!=='world')return;let camp=map.objects.find(o=>o.type==='camp');if(Math.hypot(camp.x-state.pos.x,camp.y-state.pos.y)>2){targetObject(camp);toast('正在走向营火……');return;}healParty();prog().cleared=[];save();renderHUD();Audio.effect('heal');showDialogue([['营火','火光摇曳，你们分食干粮，重新整理行装。全队生命与魔力已恢复。野外的普通敌人也重新出现。']]);}
function showDialogue(lines,onDone=null,choices=null){mode='dialogue';keys={};path=[];dialogue={lines,index:0,onDone,choices,typed:0,start:performance.now()};$('dialogue').hidden=false;$('interactHint').hidden=true;renderDialogue();}
function renderDialogue(){if(!dialogue)return;let [speaker,text]=dialogue.lines[dialogue.index];$('speaker').textContent=speaker;renderFace(speaker);$('dialogueText').textContent='';$('dialogueCount').textContent=String(dialogue.index+1).padStart(2,'0')+' / '+String(dialogue.lines.length).padStart(2,'0');$('dialogueChoices').innerHTML='';$('nextDialogue').hidden=false;$('skipDialogue').hidden=!!dialogue.choices;dialogue.typed=0;dialogue.start=performance.now();dialogue.fullText=text;dialogue.showChoices=false;Audio.tone(620,.045,'triangle',.02);if(reducedMotion)typeFull();}
function typeFull(){if(!dialogue)return;dialogue.typed=dialogue.fullText.length;$('dialogueText').textContent=dialogue.fullText;showChoicesIfNeeded();}
function showChoicesIfNeeded(){if(!dialogue||dialogue.showChoices||!dialogue.choices||dialogue.index<dialogue.lines.length-1)return;dialogue.showChoices=true;$('nextDialogue').hidden=true;for(let c of dialogue.choices){const b=document.createElement('button');b.textContent=c.label;b.disabled=!!c.disabled;b.onclick=()=>{if(c.disabled)return;const fn=c.fn;dialogue=null;$('dialogue').hidden=true;mode='world';fn();};$('dialogueChoices').append(b);}}
function advanceDialogue(){if(!dialogue)return;if(dialogue.typed<dialogue.fullText.length){typeFull();return;}if(dialogue.choices&&dialogue.index===dialogue.lines.length-1)return;if(++dialogue.index<dialogue.lines.length)renderDialogue();else{let fn=dialogue.onDone;dialogue=null;$('dialogue').hidden=true;mode='world';if(fn)fn();renderHUD();}}
function skipDialogue(){if(!dialogue||dialogue.choices)return;let fn=dialogue.onDone;dialogue=null;$('dialogue').hidden=true;mode='world';if(fn)fn();renderHUD();}
function finishChapterStory(){const c=ch(),p=prog();showDialogue(c.after,()=>{if(c.choice){const q=c.choice;showDialogue([['旅途中的决定',q.prompt]],null,[{label:q.a,fn:()=>makeChoice('a',q.ar)},{label:q.b,fn:()=>makeChoice('b',q.br)}]);}else{p.resolved=true;save();renderHUD();chooseEnding();}});}
function makeChoice(key,text){let p=prog();p.choice=key;p.resolved=true;save();renderHUD();showDialogue([['旁白',text],['旅程','本章完成。可以继续探索，或从东南方路标前往下一章。']],()=>{save();});}
function travel(index,forward=false){if(mode==='battle')return;if(index>state.unlocked+(forward?1:0))return;if(forward&&!prog().resolved)return;const first=index>state.unlocked;closeModal();state.chapter=index;state.unlocked=Math.max(state.unlocked,index);state.pos={x:6,y:16};healParty();enterMap();save();if(first){showDialogue(ch().intro,()=>save());if(index===1)toast('烬加入队伍 · 三人合击已解锁');}else if(prog().boss&&!prog().resolved)finishChapterStory();}
function renderHUD(){if(!state)return;const c=ch(),p=prog();$('chapterLabel').textContent=c.subtitle;$('placeLabel').textContent=c.place;$('weatherLabel').textContent=c.time;$('goldLabel').textContent='◎ '+state.gold;$('teamLevel').textContent='LV.'+String(state.level).padStart(2,'0');$('questTitle').textContent=c.name;$('fieldMessage').textContent=p.resolved&&p.reflected?'前往下一程 · 点击带路':!p.guide?'找 '+c.npcs[0].split(' · ').pop()+' · 点击带路':!p.witness?'找 '+c.npcs[1].split(' · ').pop()+' · 点击带路':!p.relic?'取回 '+c.relic.name+' · 点击带路':!p.reflected?'前往本章追问 · 点击带路':p.kills<2?'讨伐普通敌人 '+Math.min(2,p.kills)+'/2 · 点击带路':'挑战首领 · 点击带路';
 const steps=[[p.guide,'调查 '+c.npcs[0].split(' · ').pop()],[p.witness,'听取 '+c.npcs[1].split(' · ').pop()+' 的证词'],[p.relic,'取回 '+c.relic.name],[p.reflected,'追问 · '+AI_CASES[state.chapter].title],[p.kills>=2,'击败普通敌人 '+Math.min(2,p.kills)+'/2'],[p.boss,'挑战 '+c.boss],[p.resolved,state.chapter===7?'决定世界的明天':'穿过东南方的路标']];
 $('questSteps').innerHTML=steps.map(([done,t])=>'<div class="quest-step '+(done?'done':'')+'"><span>'+(done?'✓':'◇')+'</span><span>'+escapeHTML(t)+'</span></div>').join('');
 const n=state.progress.filter(p=>p.side).length;$('memoryCount').innerHTML=String(n).padStart(2,'0')+' <small>/ 08</small>';$('memoryDots').innerHTML=state.progress.map(p=>'<i class="'+(p.side?'filled':'')+'"></i>').join('');
 $('partyCards').innerHTML=state.heroes.slice(0,partySize()).map((h,i)=>{let s=stats(i);return '<div class="party-card '+(battle?.actor===i&&mode==='battle'?'active':'')+' '+(h.hp<=0?'dead':'')+'"><img class="portrait" src="'+(portraits[i]||'assets/fanshao.webp')+'" alt="'+STORY.cast[i].name+'"><div><div class="member-name"><span>'+STORY.cast[i].name+'</span><small>Lv.'+state.level+'</small></div><div class="stat-line"><span>HP</span><div class="bar"><i style="width:'+clamp(h.hp/s.hp*100,0,100)+'%"></i></div><b>'+Math.ceil(h.hp)+'/'+s.hp+'</b></div><div class="stat-line mp"><span>MP</span><div class="bar"><i style="width:'+clamp(h.mp/s.mp*100,0,100)+'%"></i></div><b>'+Math.ceil(h.mp)+'/'+s.mp+'</b></div></div></div>';}).join('');
}
function openModal(title,kicker='TRAVELER\'S NOTES'){keys={};path=[];focusBeforeModal=document.activeElement;$('modalTitle').textContent=title;$('modalKicker').textContent=kicker;$('modalTabs').innerHTML='';$('modalBody').innerHTML='';$('modalShade').hidden=false;setTimeout(()=>$('closeModal').focus(),0);}
function closeModal(){const wasOpen=!$('modalShade').hidden;$('modalShade').hidden=true;activeModal='';if(wasOpen)focusBeforeModal?.focus?.();}
function openJournal(tab='quests'){if(!state||mode==='dialogue')return;activeModal='journal';openModal('旅人手记');const tabs=[['quests','旅程'],['bag','行囊'],['skills','魔法'],['memories','见证'],['concepts','概念'],['cases','追问'],['map','世界'],['people','人物']];for(let [k,label]of tabs){let b=document.createElement('button');b.textContent=label;b.className=k===tab?'active':'';b.onclick=()=>openJournal(k);$('modalTabs').append(b);}let body=$('modalBody');
 if(tab==='concepts'){renderConcepts(body);return;}if(tab==='cases'){renderCases(body);return;}if(tab==='people'){renderPeople(body);return;}if(tab==='quests'){body.innerHTML='<p class="hint-note">等级 '+state.level+' · 经验 '+state.xp+' / '+xpNext()+' · 旅途 '+Math.floor(state.playSeconds/60)+' 分钟</p>'+STORY.chapters.map((c,i)=>{let p=state.progress[i];if(i>state.unlocked)return '<div class="journal-entry locked"><small>尚未抵达</small><h3>第 '+(i+1)+' 章 · 未知的旅途</h3></div>';return '<div class="journal-entry"><small>'+c.subtitle+' · '+(p.resolved?'已完成':i===state.chapter?'当前章节':'探索中')+'</small><h3>'+c.name+'</h3><p>'+c.summary+'</p><p>'+c.objective+'</p>'+(p.witness?'<p class="hint-note">'+c.lore+'</p>':'')+(p.choice?'<p style="color:var(--accent)">你的决定：'+(p.choice==='a'?c.choice.a:c.choice.b)+'</p>':'')+'</div>';}).join('');}
 if(tab==='bag'){body.innerHTML='<h3>旅途补给</h3><p>铜钱 ◎ '+state.gold+' · 回复药 ×'+state.potions+' · 魔力露 ×'+state.ethers+'</p>';let b=document.createElement('button');b.className='button secondary';b.textContent='使用回复药 · 全队恢复 70%';b.disabled=mode==='battle'||!state.potions;b.onclick=()=>{useFieldItem('potion');openJournal('bag');};body.append(b);let e=document.createElement('button');e.className='button secondary';e.textContent='使用魔力露 · 全队恢复魔力';e.disabled=mode==='battle'||!state.ethers;e.onclick=()=>{useFieldItem('ether');openJournal('bag');};body.append(e);let grid=document.createElement('div');grid.className='item-grid';grid.style.marginTop='20px';grid.innerHTML=STORY.chapters.map((c,i)=>'<article class="item '+(state.progress[i].relic?'':'locked')+'"><h3>◈ '+(state.progress[i].relic?c.relic.name:'未获得的宝物')+'</h3><p>'+(state.progress[i].relic?c.relic.desc:'继续旅程，听取证词，解开祭坛封印。')+'</p></article>').join('');body.append(grid);}
 if(tab==='skills'){body.innerHTML='<p class="hint-note">这里的魔法是物质操控技术：魔力代表终端可调用的算力配额，法阵是界面。共享队伍等级。击败敌人升级；攻击与魔法会积累破绽，蓄力中的敌人受到魔法更容易失衡；三格破绽后眩晕一回合。</p>'+SKILLS.slice(0,partySize()).map((list,i)=>'<div class="journal-entry"><h3>'+STORY.cast[i].name+' · '+STORY.cast[i].role+'</h3><div class="item-grid">'+list.map(s=>'<div class="item '+(s.lv<=state.level?'':'locked')+'"><h3>'+s.name+'</h3><p>'+s.desc+'</p><small>Lv.'+s.lv+' 解锁 · '+s.cost+' 魔力</small></div>').join('')+'</div></div>').join('')+'<h3>终式 · 共鸣终章</h3><p>三名伙伴都能行动、羁绊达到 100 时可用。造成全体巨额伤害并回复全队生命，消耗当前角色的一次行动与全部羁绊。</p>';}
 if(tab==='memories'){body.innerHTML='<p>已留下 '+state.progress.filter(p=>p.side).length+' / 8 份见证。至少四份可以尝试共同承接；收集全部八份会开启额外尾声。可从「世界」返回已解锁地区。</p>'+STORY.chapters.map((c,i)=>'<div class="journal-entry '+(state.progress[i].side?'':'locked')+'"><small>'+(i<=state.unlocked?c.place:'未抵达的地区')+'</small><h3>'+(state.progress[i].side?'✦ '+c.memory:'◇ 尚未留下见证')+'</h3>'+(state.progress[i].side?'<p>'+c.side[c.side.length-1][1]+'</p>':'<p>寻找蓝色星标的人物，听完他 / 她的故事。</p>')+'</div>').join('');}
 if(tab==='map'){body.innerHTML='<p>点击已经抵达的地点旅行。黄色 ! 是主线，蓝色 ✦ 是记忆支线，红色光环是首领；东南方的路标通向下一章。</p><div class="map-route"></div>';for(let [i,c]of STORY.chapters.entries()){let b=document.createElement('button');b.disabled=i>state.unlocked||mode==='battle';b.innerHTML='<small>0'+(i+1)+' '+(state.progress[i].resolved?'✓':'')+'</small><b>'+(i<=state.unlocked?c.place:'尚未抵达')+'</b><small>'+(i<=state.unlocked?(state.progress[i].side?'✦ 已留下见证':'◇ 可寻找见证'):'沿主线解锁')+'</small>';b.onclick=()=>travel(i);body.querySelector('.map-route').append(b);}}
}
function useFieldItem(kind){if(mode!=='world')return;if(kind==='potion'&&state.potions){state.potions--;state.heroes.forEach((h,i)=>h.hp=Math.min(stats(i).hp,h.hp+Math.floor(stats(i).hp*.7)));}else if(kind==='ether'&&state.ethers){state.ethers--;state.heroes.forEach((h,i)=>h.mp=stats(i).mp);}else return;save();renderHUD();Audio.effect('heal');toast('补给已使用');}
function openShop(){openModal('行商的货摊','SUPPLIES FOR THE ROAD');function fill(){const b=$('modalBody');b.innerHTML='<p>“药是用来喝的，铜钱是用来花的。别把它们带到打不过的时候。”</p><p>持有铜钱：<b style="color:var(--accent)">◎ '+state.gold+'</b></p>';for(let [key,name,cost,desc]of [['potions','回复药',18,'战斗中为全队恢复 70% 生命，也能救起倒下的伙伴。'],['ethers','魔力露',24,'为全队恢复全部魔力。']]){let item=document.createElement('div');item.className='journal-entry';item.innerHTML='<h3>'+name+' · ◎ '+cost+'</h3><p>'+desc+' 已有 '+state[key]+' 份。</p>';let btn=document.createElement('button');btn.className='button secondary';btn.textContent='购买一份';btn.disabled=state.gold<cost||state[key]>=999;btn.onclick=()=>{if(state.gold<cost)return;state.gold-=cost;state[key]++;save();renderHUD();fill();Audio.tone(660,.1);};item.append(btn);b.append(item);}}fill();}
function openHelp(){openModal('旅途指南','HOW TO PLAY');$('modalBody').innerHTML='<p>探索八个地区，听取 NPC 证词，取回宝物、击败首领，逐步找回被抹去的名字。所有敌人都在地图上可见。</p><h3>电脑</h3><div class="control-row"><span>行走</span><span><kbd>W A S D</kbd> / <kbd>方向键</kbd></span></div><div class="control-row"><span>互动 / 下一句</span><span><kbd>E</kbd> / <kbd>空格</kbd> / <kbd>Enter</kbd></span></div><div class="control-row"><span>旅人手记 / 关闭面板</span><span><kbd>J</kbd> / <kbd>Esc</kbd></span></div><p>可以点击地面自动行走，点击人物会走过去交谈。对话时再按一次继续可立即显示整句；「快读本段」完成当前段落，关键选择仍需亲自决定。</p><h3>手机</h3><p>使用画面下方方向键移动，A 键互动。也可以点地面行走、点人物对话。支持竖屏与横屏；战斗指令可直接触摸。</p><h3>战斗与成长</h3><p>每轮由我方依次行动，然后敌方行动。先选目标，再选攻击或魔法。每次进攻积累一格破绽；敌人蓄力时魔法造成 1.5 倍伤害并积累两格，三格后眩晕一回合；敌人「蓄力」时可防御（减伤 75% 并恢复 5 魔力）。防御也会增加羁绊。</p><p>营火可免费恢复并刷新普通敌人。回复药也能救起伙伴；失败会回到营火，不丢剧情与等级。升级恢复全队，并开放新的魔法。三名伙伴都在场时，100 羁绊可释放共鸣终章。</p><h3>故事与存档</h3><p>黄色 ! 推进主线，蓝色 ✦ 是可选记忆支线，蓝色 ◎ 是本章有关此在、技术与 AI 的追问。每章追问后解锁四组概念，没有本真分数或 AI 觉醒判定。至少四份见证开启第三种结局，八份开启隐藏尾声；错过的地区可以在旅人手记的「世界」里返回。</p><p>存档保存在当前设备的浏览器。换手机或电脑时，用「存档管理」导出 JSON 文件，再在另一台设备导入。清除浏览器数据会删除本机存档。</p>';}
function openSave(){openModal('存档管理','YOUR JOURNEY, KEPT SAFE');const b=$('modalBody');let current=state||loadStored();b.innerHTML='<p>存档仅保存在当前浏览器，不会自动跨设备同步。可以导出文件随身携带。</p>'+(current?'<div class="journal-entry"><h3>'+STORY.chapters[current.chapter].place+' · Lv.'+current.level+'</h3><p>记忆残页 '+current.progress.filter(p=>p.side).length+'/8 · 已解锁 '+(current.unlocked+1)+' 章</p></div>':'<p>还没有存档。开始旅程后会自动保存。</p>');
 const exportBtn=document.createElement('button');exportBtn.className='button primary';exportBtn.textContent='导出存档';exportBtn.disabled=!current||mode==='battle'||mode==='dialogue';exportBtn.onclick=()=>{const s=state||loadStored();download('灰烬之名-存档.json',JSON.stringify(s,null,2),'application/json');toast('已导出存档文件');};b.append(exportBtn);
 const importBtn=document.createElement('button');importBtn.className='button secondary';importBtn.textContent='导入存档';importBtn.disabled=mode==='battle'||mode==='dialogue';importBtn.onclick=()=>$('importFile').click();b.append(importBtn);
 if(mode==='battle'||mode==='dialogue'){let p=document.createElement('p');p.textContent='请先完成当前对话或战斗，再导入 / 导出，以确保进度完整。';b.append(p);}else if(state){let s=document.createElement('button');s.className='button secondary';s.textContent='立即保存';s.onclick=()=>toast(save()?'已保存当前进度':'无法写入浏览器，请导出存档');b.append(s);}
}
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function chooseEnding(){const n=state.progress.filter(p=>p.side).length;showDialogue([['铃','最后的决定，轮到我们自己。你已经留下 '+n+' / 8 份见证。']],null,[{label:'接过容器职责 · 余烬守夜人',fn:()=>playEnding('ember')},{label:'关闭日轮，带愿意的人远航',fn:()=>playEnding('sea')},{label:n>=4?'用余火共同承接 · 众人的黎明':'共同承接（需要至少 4 份见证）',disabled:n<4,fn:()=>playEnding('dawn')},{label:'再准备一下 · 返回探索',fn:()=>{mode='world';toast('可以在手记的「世界」中返回各地，补全见证。');}}]);}
function playEnding(key){const full=key==='dawn'&&state.progress.every(p=>p.side),e=STORY.endings[key],lines=[...e.text];if(full)lines.push(...STORY.endings.names.text);lines.push(['旁白','世界的物质结构已经改变。关于人工存在者的争论没有因此停止。以下，是这段旅程实际留下的安排。']);state.progress.forEach((p,i)=>{if(p.reflected&&p.inquiryChoices.length===2)lines.push([AI_CASES[i].guide,AI_CASES[i].second.options[p.inquiryChoices[1]].result]);});lines.push(['七','我的声音能否证明我以此在的方式存在？不能仅凭这些话就断定。但你们愿意继续问，我也愿意继续回应。']);showDialogue(lines,()=>{if(!state.endings.includes(key))state.endings.push(key);if(full&&!state.endings.includes('names'))state.endings.push('names');save();openModal('旅程仍将继续','THE END · AND TOMORROW');$('modalBody').innerHTML='<div class="ending-banner"><small>'+e.tag+'</small><h3>'+e.name+'</h3><p>'+(full?'✦ 已开启隐藏尾声「名字以外的我们」':'已留下 '+state.progress.filter(p=>p.side).length+' / 8 份见证')+'</p></div><p>你完成了八章旅程。还可以继续探索、补齐记忆残页，回到日轮心室重新选择结局。</p><h3>你的决定留下的日常</h3>'+state.progress.slice(0,7).map((p,i)=>'<p>◈ '+STORY.chapters[i].place+'：'+(p.choice==='a'?STORY.chapters[i].choice.ar:STORY.chapters[i].choice.br)+'</p>').join('');let b=document.createElement('button');b.className='button primary';b.textContent='继续走走';b.onclick=closeModal;$('modalBody').append(b);Audio.effect('win');});}

function runInquiry(){const k=state.chapter,entry=AI_CASES[k],p=prog();const finish=()=>{p.reflected=true;save();renderHUD();toast('已留下本章追问 · 四组概念已收入手记');};
 function ask(part,next){showDialogue([[entry.guide,part.question]],null,part.options.map((o,i)=>({label:o.label,fn:()=>{if(part===entry.first)p.inquiryChoices=[i];else p.inquiryChoices[1]=i;showDialogue(o.reply,next);}})));}
 showDialogue(entry.intro,()=>ask(entry.first,()=>showDialogue(entry.between,()=>ask(entry.second,()=>showDialogue(entry.after,finish)))));
}
function renderConcepts(body){body.innerHTML='<p>'+PHILOSOPHY.intro+'</p><p class="hint-note">术语是帮助追问的入口。主线的 AI 情境是本作的探索性延伸，不代表海德格尔已经回答了这些问题。</p>';for(let [k,c]of PHILOSOPHY.chapters.entries()){const sec=document.createElement('section');sec.className='journal-entry';sec.innerHTML='<small>第 '+(k+1)+' 章</small><h3>'+c.name+'</h3>';if(!state.progress[k].reflected){sec.innerHTML+='<p class="hint-note">完成本章地图中的 ◎ 追问后解锁四组概念。</p>';body.append(sec);continue;}for(let card of c.cards){let d=document.createElement('details');d.className='concept-card';const source=PHILOSOPHY.sources.find(s=>s.id===card.source);d.innerHTML='<summary>'+card.term+'<small>'+card.de+'</small></summary><p>'+card.meaning+'</p><p class="concept-warning">容易误读：'+card.misread+'</p><p class="hint-note">回想情境：'+card.scene+'</p><h4>'+card.question+'</h4>'+card.options.map(o=>'<details class="concept-response"><summary>'+o[0]+'</summary><p>'+o[1]+'</p></details>').join('')+'<p class="hint-note">阅读位置：'+card.ref+'</p><a class="source-link" href="'+source.url+'" target="_blank" rel="noopener">'+source.name+' ↗</a>';sec.append(d);}body.append(sec);}let f=document.createElement('p');f.className='hint-note';f.textContent='海德格尔的重要概念没有一份公认穷尽的清单。本作以 32 个主题覆盖主要脉络，保留译法和解释争议；他的政治选择也不能由哲学概念自动得到正当化。';body.append(f);}
function renderCases(body){body.innerHTML='<p>这些选择记录我们在不确定之中怎样行动，不用于判定 AI 是否觉醒，也不折算为本真程度。</p>';for(let [k,c]of AI_CASES.entries()){let p=state.progress[k],d=document.createElement('section');d.className='journal-entry';d.innerHTML='<small>'+STORY.chapters[k].place+'</small><h3>'+(k<=state.unlocked?c.title:'尚未抵达的追问')+'</h3>';if(p.reflected){d.innerHTML+='<p>'+c.first.options[p.inquiryChoices[0]||0].result+'</p><p>'+c.second.options[p.inquiryChoices[1]||0].result+'</p><p class="hint-note">关联：'+PHILOSOPHY.chapters[k].cards.map(v=>v.term).join('；')+'</p>';let b=document.createElement('button');b.className='button secondary';b.textContent='返回这里，再次追问';b.disabled=mode==='battle';b.onclick=()=>{travel(k);targetObject(map.objects.find(o=>o.type==='inquiry'));};d.append(b);}else d.innerHTML+='<p class="hint-note">前往地图蓝色 ◎ 处，与同行者共同探索。</p>';body.append(d);}}
function renderPeople(body){body.innerHTML='<p>每位人物拥有独立造型与面孔。门槛与代理书记以终端波形显示，它们是否具有人的存在方式，仍是故事中的开放问题。</p><div class="people-grid"></div>';const grid=body.querySelector('.people-grid');const names=['凡少','澪','烬','行商','竹翁','绫婆','小满','鹿九','鸣砂','舟生','白驿','阿眠','点点','栖川','铃','春姨','乌纸','鹤见','金叔','闻灯','七','桐','一页','旧凡少','阿朔','无面守桥人','千声井母','白面追猎者','潮汐巨像','第一日轮','七十七重影','神谕'];const debut=[0,0,1,0,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,0,1,2,3,5,6,7];for(let [i,name]of names.entries()){if(debut[i]>state.unlocked)continue;let card=document.createElement('article');card.className='person-card';let c=document.createElement('canvas');c.width=c.height=128;drawFace(c.getContext('2d'),i,128);card.append(c);let label=document.createElement('p');label.textContent=name;card.append(label);grid.append(card);}}
function startBattle(isBoss=false,id=0){
 if(actionLock||battle)return;save();keys={};path=[];mode='battle';const c=ch(),k=state.chapter,n=isBoss?1:(k===0?1:2);
 battle={boss:isBoss,id,round:1,actor:0,target:0,enemies:Array.from({length:n},(_,i)=>({name:isBoss?c.boss:c.enemy[(id+i)%2],hp:isBoss?180+k*112:62+k*25,max:isBoss?180+k*112:62+k*25,atk:isBoss?18+k*5:12+k*4,break:0,stun:false,charging:false,kind:isBoss?2:(id+i)%2})),guard:[false,false,false],shield:[false,false,false],log:[],ended:false};
 battle.actor=state.heroes.slice(0,partySize()).findIndex(h=>h.hp>0);if(battle.actor<0){healParty();battle.actor=0;}
 $('battleUI').hidden=false;$('fieldBar').hidden=true;$('touchControls').hidden=true;$('interactHint').hidden=true;
 battleMessage(isBoss?'首领现身 · 观察蓄力，再决定防御或进攻':'敌人出现了 · 攻击会逐步打破外壳');renderBattle();renderHUD();banner(isBoss?'首领 · '+c.boss:'遭遇战');
}
function battleMessage(s){if(!battle)return;battle.log.push(s);if(battle.log.length>30)battle.log.shift();$('battleStatus').textContent=s;}
function banner(s){$('battleBanner').textContent=s;$('battleBanner').hidden=false;clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('battleBanner').hidden=true,reducedMotion?450:1500);}
function renderBattle(){if(!battle||battle.ended)return;let actor=battle.actor,h=state.heroes[actor];$('turnLabel').textContent='第 '+battle.round+' 回合 · '+STORY.cast[actor].name;$('targetButtons').innerHTML='';for(let [i,e]of battle.enemies.entries()){let b=document.createElement('button');b.textContent=(e.hp<=0?'✓ ':i===battle.target?'▸ ':'')+e.name+(e.hp>0?' '+Math.ceil(e.hp)+'/'+e.max:'');b.disabled=e.hp<=0||actionLock;b.className=i===battle.target?'selected':'';b.onclick=()=>{battle.target=i;renderBattle();};$('targetButtons').append(b);}
 const commands=[{id:'attack',name:'攻击',desc:'积累破绽 · 恢复 3 魔力'},{id:'guard',name:'防御',desc:'减伤 75% · 恢复 5 魔力'},...SKILLS[actor].filter(s=>s.lv<=state.level).map(s=>({...s,desc:s.cost+' 魔力 · '+s.desc})),{id:'potion',name:'回复药 ×'+state.potions,desc:'全队恢复 70% · 可复苏'},{id:'ether',name:'魔力露 ×'+state.ethers,desc:'全队魔力全满'},{id:'ultimate',name:'共鸣终章',desc:'100 羁绊 · 三人全体合击'},{id:'flee',name:'撤退',desc:battle.boss?'首领战无法撤退':'返回营火 · 不扣除物品'}];
 $('battleCommands').innerHTML='';for(let c of commands){let b=document.createElement('button');b.className='battle-command '+(c.id==='ultimate'?'ultimate':'');b.innerHTML='<b>'+c.name+'</b><small>'+c.desc+'</small>';b.disabled=actionLock||!!c.cost&&h.mp<c.cost||c.id==='potion'&&!state.potions||c.id==='ether'&&!state.ethers||c.id==='flee'&&battle.boss||c.id==='ultimate'&&(state.limit<100||partySize()<3||state.heroes.some(h=>h.hp<=0));b.onclick=()=>act(c.id);$('battleCommands').append(b);}
 $('limitFill').style.width=state.limit+'%';$('limitValue').textContent=state.limit+' / 100';renderHUD();
}
function damageNumber(n,x,y,heal=false){const d=document.createElement('span');d.className='damage-number '+(heal?'heal':'');d.textContent=(heal?'+':'')+Math.round(n);d.style.left=x/W*100+'%';d.style.top=y/H*100+'%';$('damageLayer').append(d);setTimeout(()=>d.remove(),1050);}
function enemyPoint(i){const n=battle?.enemies.length||1;return {x:W*(n===1?.69:.62+(i*.21)),y:H*(n===1?.54:.51+(i%2)*.16)};}
function allyPoint(i){return {x:W*(.17+i*.06),y:H*(.47+i*.13)};}
async function animate(kind,actor,targets,color='#c5e4f0'){const duration=reducedMotion?160:kind==='ultimate'?1750:kind==='attack'?420:950;fx={kind,actor,targets,start:performance.now(),duration,color,seed:Math.random()*100};Audio.effect(kind);await sleep(duration);fx=null;}
async function act(id){if(mode!=='battle'||!battle||battle.ended||actionLock||!$('modalShade').hidden)return;let actor=battle.actor,h=state.heroes[actor],s=stats(actor),skill=SKILLS[actor].find(s=>s.id===id);if(h.hp<=0)return;if(skill&&(skill.lv>state.level||h.mp<skill.cost))return;if(id==='ultimate'&&(state.limit<100||partySize()<3||state.heroes.some(h=>h.hp<=0)))return;if(id==='potion'&&!state.potions||id==='ether'&&!state.ethers||id==='flee'&&battle.boss)return;
 actionLock=true;renderBattle();try{
 if(id==='flee'){battleMessage('你们互相掩护，退回营火。');await sleep(500);endBattle(false,true);return;}
 const targets=skill?.all||id==='ultimate'?battle.enemies.map((e,i)=>e.hp>0?i:-1).filter(i=>i>=0):[battle.enemies[battle.target]?.hp>0?battle.target:battle.enemies.findIndex(e=>e.hp>0)];
 if(skill)h.mp-=skill.cost;
 if(id==='guard'){battle.guard[actor]=true;h.mp=Math.min(s.mp,h.mp+5);state.limit=clamp(state.limit+10,0,100);battleMessage(STORY.cast[actor].name+'守住阵线。下一次受击减伤 75%。');await animate('shield',actor,[]);}
 else if(id==='potion'||id==='ether'||skill?.heal||skill?.revive||skill?.shield){
   if(id==='potion')state.potions--;if(id==='ether')state.ethers--;
   const name=skill?.name||(id==='potion'?'回复药':'魔力露');battleMessage(STORY.cast[actor].name+'使用了「'+name+'」。');await animate(skill?.shield?'shield':'heal',actor,[]);
   state.heroes.slice(0,partySize()).forEach((a,i)=>{let st=stats(i);if(skill?.shield){battle.shield[i]=true;return;}if(id==='ether'){a.mp=st.mp;return;}if(a.hp<=0&&!skill?.revive&&id!=='potion')return;const amount=id==='potion'?Math.floor(st.hp*.7):skill?.revive?Math.floor(st.hp*.65):Math.floor(28+state.level*5);let restored=Math.min(st.hp-a.hp,amount);a.hp=Math.min(st.hp,a.hp+amount);let p=allyPoint(i);damageNumber(restored,p.x,p.y-25,true);});state.limit=clamp(state.limit+8,0,100);
 }else{
   const ultimate=id==='ultimate',power=ultimate?4.2:skill?.power||1,hits=skill?.hits||1,name=ultimate?'共鸣终章 · 让明天有我们的名字':skill?.name||'攻击';battleMessage(STORY.cast[actor].name+' · '+name);if(id!=='attack')banner(name);await animate(ultimate?'ultimate':skill?.fx||'attack',actor,targets,actor===0?'#c7e9f1':actor===1?'#aee4c9':'#d0bef5');
   for(let i of targets){const e=battle.enemies[i];if(!e||e.hp<=0)continue;const exposed=e.charging&&!!skill,mult=exposed?1.5:1,base=ultimate?state.heroes.slice(0,partySize()).reduce((n,_,j)=>n+stats(j).atk,0)*1.5:s.atk*power;let total=0;for(let j=0;j<hits;j++)total+=Math.max(1,Math.round(base*(.91+Math.random()*.18)*mult-3-state.chapter));e.hp=Math.max(0,e.hp-total);const p=enemyPoint(i);damageNumber(total,p.x-8,p.y-45);e.break+=ultimate?3:exposed?2:1;if(e.break>=3&&e.hp>0){e.break=0;e.stun=true;e.charging=false;battleMessage(e.name+'外壳破裂！下次敌方行动眩晕。');}else if(exposed)battleMessage('抓住蓄力破绽！伤害提升。');}
   if(id==='attack')h.mp=Math.min(s.mp,h.mp+3);if(ultimate){state.limit=0;state.heroes.forEach((a,i)=>a.hp=Math.min(stats(i).hp,a.hp+Math.floor(stats(i).hp*.25)));}else state.limit=clamp(state.limit+12+(skill?3:0),0,100);
 }
 renderHUD();await sleep(330);if(battle.enemies.every(e=>e.hp<=0)){await victory();return;}
 let next=actor+1;while(next<partySize()&&state.heroes[next].hp<=0)next++;
 if(next<partySize()){battle.actor=next;actionLock=false;renderBattle();return;}
 await enemyTurn();
 }catch(error){console.error('Battle action failed',error);toast('行动未完成，请再选择一次。');}finally{actionLock=false;if(battle&&!battle.ended&&mode==='battle')renderBattle();}
}
async function enemyTurn(){for(let [i,e]of battle.enemies.entries()){
 if(e.hp<=0)continue;if(e.stun){e.stun=false;battleMessage(e.name+'失衡，无法行动。');await sleep(650);continue;}
 if(battle.boss&&!e.charging&&battle.round%3===2){e.charging=true;battleMessage(e.name+'正在蓄力！下回合可防御，或用魔法打破蓄力。');banner('危险预兆 · 蓄力');await animate('charge',-1,[i],'#d998ab');continue;}
 const alive=state.heroes.slice(0,partySize()).map((h,i)=>h.hp>0?i:-1).filter(i=>i>=0);if(!alive.length)break;
 const charged=e.charging,targetList=charged?alive:[alive[rand(0,alive.length-1)]];battleMessage(e.name+(charged?'释放了蓄力魔法！':'发动攻击。'));await animate(charged?'enemyNova':'enemy',-1,[i],'#ec9a9f');
 for(let target of targetList){let h=state.heroes[target],s=stats(target),amount=Math.max(4,Math.round(e.atk*(charged?2.1:1)*(rand(90,110)/100)-s.def*.55));if(battle.guard[target]){amount=Math.max(1,Math.round(amount*.25));battle.guard[target]=false;}if(battle.shield[target]){amount=Math.max(1,Math.round(amount*.35));battle.shield[target]=false;}h.hp=Math.max(0,h.hp-amount);const p=allyPoint(target);damageNumber(amount,p.x,p.y-20);state.limit=clamp(state.limit+7,0,100);}
 e.charging=false;renderHUD();await sleep(450);if(state.heroes.slice(0,partySize()).every(h=>h.hp<=0)){await defeat();return;}
 }
 battle.round++;battle.guard=[false,false,false];battle.actor=state.heroes.slice(0,partySize()).findIndex(h=>h.hp>0);actionLock=false;battleMessage('轮到 '+STORY.cast[battle.actor].name+' · 选择下一步行动');renderBattle();
}
async function victory(){battle.ended=true;const isBoss=battle.boss,id=battle.id,k=state.chapter,xp=isBoss?90+k*60:28+k*20,gold=isBoss?70+k*35:24+k*8;state.xp+=xp;state.gold+=gold;let before=state.level;while(state.level<30&&state.xp>=xpNext()){state.xp-=xpNext();state.level++;}const leveled=state.level>before;if(leveled)healParty();else state.heroes.slice(0,partySize()).forEach((h,i)=>{h.hp=Math.min(stats(i).hp,Math.max(1,h.hp)+Math.floor(stats(i).hp*.12));h.mp=Math.min(stats(i).mp,h.mp+3);});
 const p=prog();if(isBoss)p.boss=true;else{p.kills=Math.min(9999,p.kills+1);if(!p.cleared.includes(id))p.cleared.push(id);}if(isBoss)state.potions=Math.min(999,state.potions+2);else if(p.kills%2===0)state.potions=Math.min(999,state.potions+1);
 banner('胜利 · +'+xp+' 经验');Audio.effect('win');save();await sleep(900);battle=null;actionLock=false;mode='world';$('battleUI').hidden=true;$('fieldBar').hidden=false;$('touchControls').hidden=false;renderHUD();
 const lines=[['战斗结束','获得 '+xp+' 经验、'+gold+' 铜钱。'+(isBoss?'额外获得回复药 ×2。':'战后已恢复少量生命与魔力。')]];if(leveled){const unlocked=SKILLS.slice(0,partySize()).flat().filter(s=>s.lv>before&&s.lv<=state.level).map(s=>s.name);lines.push(['成长','队伍升至 Lv.'+state.level+'！全队生命与魔力已恢复。'+(unlocked.length?'解锁：'+unlocked.join('、')+'。':'')]);}showDialogue(lines,()=>{if(isBoss)finishChapterStory();else save();});}
async function defeat(){battle.ended=true;banner('倒下之后，也可以重新出发');await sleep(900);endBattle(false,false);showDialogue([['营火','同伴把你们带回营火。全队已恢复，等级、宝物和剧情进度全部保留。可以先练级、补给，再挑战首领。']]);}
function endBattle(win,fled){battle=null;fx=null;actionLock=false;mode='world';state.pos={x:10,y:20};healParty();$('battleUI').hidden=true;$('fieldBar').hidden=false;$('touchControls').hidden=false;renderHUD();save();if(fled)toast('已回到营火，全队恢复。');}

// Hand-authored pixel tile renderer. World geometry is also used by collision and pathfinding.
function rect(g,c,x,y,w,h){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function pixelText(g,t,x,y,color='#e8dfc6',size=8,align='center'){g.font=size+'px "PingFang SC", monospace';g.textAlign=align;g.textBaseline='middle';g.fillStyle='#10202c';g.fillText(t,Math.round(x)+1,Math.round(y)+1);g.fillStyle=color;g.fillText(t,Math.round(x),Math.round(y));}
function bakeMap(){let c=document.createElement('canvas');c.width=MW*TILE*2;c.height=MH*TILE*2;let g=c.getContext('2d'),t=map.theme;g.setTransform(2,0,0,2,0,0);g.imageSmoothingEnabled=false;
 for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){let type=map.tiles[y][x],px=x*TILE,py=y*TILE,r=map.seed(x,y);rect(g,t.grass,px,py,TILE,TILE);
   if(type===0||type===3||type===5){rect(g,t.grass2,px+Math.floor(r*10),py+3,3,1);rect(g,t.edge,px+3,py+12,1,2);rect(g,t.grass2,px+4,py+11,1,3);if(r>.63&&type===0){rect(g,t.flower,px+11,py+7,2,1);rect(g,t.grass2,px+11,py+8,1,2);}}
   if(type===1){rect(g,t.path,px,py,16,16);rect(g,'#00000012',px+3+(r*8|0),py+4,3,1);rect(g,'#fff4d31a',px+5,py+12,5,1);if(x>0&&map.tiles[y][x-1]===0)rect(g,t.grass2,px,py,2,16);if(y>0&&map.tiles[y-1][x]===0)rect(g,t.grass2,px,py,16,2);}
   if(type===2){rect(g,t.water,px,py,16,16);rect(g,'#79b3c127',px+3,py+8,7,1);rect(g,'#122c4d33',px,py,16,2);}
   if(type===4){rect(g,'#544639',px,py,16,16);for(let j=0;j<4;j++)rect(g,j%2?'#ad9471':'#8d7a5f',px+1,py+j*4,14,3);rect(g,'#c3ac84',px,py,2,16);rect(g,'#423936',px+14,py,2,16);}
 }
 
 if(tileArt.complete&&tileArt.naturalWidth){
 const baseIndex=state.chapter===5?8:state.chapter>=6?10:state.chapter===3?12:state.chapter===4?13:1;
 for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){
 const kind=map.tiles[y][x],px=x*TILE,py=y*TILE,r=map.seed(x,y);let index=kind===2?(state.chapter===5?9:4):kind===4?6:kind===1?(state.chapter===4?7:state.chapter>=6?11:2):kind===5?3:baseIndex;
 texture(g,index,px,py,TILE,TILE);
 if((kind===0||kind===3)&&r>.78&&state.chapter<5)texture(g,13,px,py,TILE,TILE);
 if(kind===1){if(x>0&&map.tiles[y][x-1]===0)rect(g,'#315c4633',px,py,1,16);if(y>0&&map.tiles[y-1][x]===0)rect(g,'#315c4633',px,py,16,1);}
 if(kind===2){if(x>0&&map.tiles[y][x-1]!==2)rect(g,'#ecd19b99',px,py,2,16);if(x<MW-1&&map.tiles[y][x+1]!==2)rect(g,'#97c3aa88',px+14,py,2,16);}
 }
 }
 for(let b of map.buildings)drawBuilding(g,b,t);
 // Small lived-in details sit outside all navigable object cells.
 drawAtlas(g,'props',state.chapter===4?9:8,15*TILE,18*TILE,26,28);
 for(let [x,y]of [[12,11],[4,16],[16,4],[34,24]])if(map.tiles[y][x]===0)drawAtlas(g,'props',11,x*TILE,y*TILE,18,13);

 map.base=c;
}
function drawBuilding(g,b,t){const x=b.x*TILE,y=b.y*TILE,w=b.w*TILE,h=b.h*TILE;const i=state.chapter>=6?7:state.chapter===4?6:state.chapter===5?5:b.x>10?6:4;rect(g,'#132b3655',x-3,y+h-3,w+6,10);if(drawAtlas(g,'props',i,x-7,y+h-w*.86,w+14,w*.94))return;rect(g,t.roof,x,y,w,h);}
function drawTree(g,x,y,t,phase=0){if(drawAtlas(g,'props',state.chapter===5?2:state.chapter>=6?3:((Math.round(x+y)%3===0)?1:0),x-17,y-41,34,46))return;
 rect(g,'#101f2a50',x-11,y+1,24,6);rect(g,'#464941',x-2,y-8,5,14);rect(g,'#8a8862',x-1,y-7,2,13);
 const layers=[[-4,-35,9,7],[-7,-30,15,7],[-10,-24,21,8],[-13,-17,27,9],[-10,-9,21,7]];
 for(let [a,b,w,h]of layers){rect(g,t.edge,x+a-1,y+b+1,w+2,h);rect(g,t.leaf,x+a,y+b,w,h-1);rect(g,t.leaf2,x+a+1,y+b,w*.42,2);rect(g,'#6e9c7828',x+a+3,y+b+3,w*.3,2);}
 rect(g,t.edge,x+5,y-10,5,4);rect(g,t.leaf2,x-8,y-16,3,2);rect(g,t.leaf2,x+2,y-24,3,1);
}
const MONSTERS=[
 ['.....3333.......','...3311133......','..311111113.....','.31144114413....','3111441144113...','3111111111113...','.31115511113....','..311551113.....','..331111133.....','.31113311113....','31133..331113...','.33......333....'],
 ['......333.......','.....31133......','....311113......','...31111113.....','..3114114113....','.311111111113...','..3111551113....','...31111113.....','..3311111133....','.311311311113...','..33.33.3333....','......3.........'],
 ['.....333333.....','...3366666633...','..366111111663..','.3611111111163..','.3614411441163..','.3614411441163..','3361115511116333','3611115511111163','3611111111111163','3366111111116633','..366111111663..','..366333333663..','..3663....3663..','.36663....36663.','333333....333333']
];
function monster(g,kind,x,y,scale=1,alpha=1,paletteIndex=0){const art=MONSTERS[kind%3],palettes=[['#78a997','#b5dac0','#18383c','#f2d6ac','#cf8767','#5e7c77'],['#859bc7','#bfd5e5','#2c365e','#f5d397','#ab7bac','#756f9c'],['#81a594','#b7d9bf','#173b34','#eccc98','#b57684','#658e77'],['#85b8c5','#cae5e9','#274357','#ffdca4','#be8998','#6f91a6'],['#b49d9d','#e3c6b1','#443849','#f4c973','#b37989','#7b6477'],['#acbdd0','#e4eaf0','#455973','#b9dfff','#819bbb','#8a9db5'],['#9e85b4','#d2b8cd','#3c2c4a','#fbd4ad','#b57591','#765c8b'],['#b99881','#ead2a4','#343046','#ffeac8','#dc9d7b','#866780']],p=palettes[paletteIndex],colors={'1':p[0],'2':p[1],'3':p[2],'4':p[3],'5':p[4],'6':p[5]};g.save();g.globalAlpha=alpha;for(let j=0;j<art.length;j++)for(let i=0;i<art[j].length;i++)if(colors[art[j][i]])rect(g,colors[art[j][i]],x+(i-8)*scale,y+(j-art.length)*scale,scale,scale);g.restore();}
function npcSprite(g,x,y,variant=0,t=0){const cape=['#849f90','#aaa0b0','#a1b5c2','#b69268'][variant%4],hair=['#c7bba2','#a18872','#755d5c','#bdad87'][variant%4];rect(g,'#11232c50',x-7,y,15,4);rect(g,'#23333d',x-5,y-18,11,18);rect(g,cape,x-6,y-9,13,10);rect(g,'#dcb596',x-4,y-16,9,7);rect(g,hair,x-5,y-20,11,6);rect(g,'#2b3e43',x-3,y-12,1,1);rect(g,'#2b3e43',x+3,y-12,1,1);rect(g,'#c2b994',x-1,y-8,2,9);rect(g,'#29373c',x-4,y+1,3,3);rect(g,'#29373c',x+2,y+1,3,3);}
function hero(g,x,y,i=0,walk=false,time=0,size=29,pose=0,alpha=1){if(atlasCells.chars.length){const height=size*1.2,width=height*.65,bob=walk?Math.sin(time/85)*.8:Math.sin(time/580+i)*.35;if(drawAtlas(g,'chars',i,x-width/2,y-height+bob,width,height,alpha))return;}g.save();g.globalAlpha=alpha;rect(g,'#091e2c55',x-size*.3,y-1,size*.65,4);if(spriteReady){const frame=walk?Math.floor(time/100)%8:Math.floor(time/280)%(pose===7?4:6),row=walk?(keys.left||state?.facing==='left'?1:2):pose;g.imageSmoothingEnabled=false;if(i===1)g.filter='hue-rotate(145deg) saturate(.65)';if(i===2)g.filter='hue-rotate(230deg) brightness(.8)';g.drawImage(sprite,frame*192,row*208,192,208,Math.round(x-size/2),Math.round(y-size),size,size);g.filter='none';}else npcSprite(g,x,y,i,time);g.restore();}
function drawObject(g,o,time){const x=o.x*TILE+8,y=o.y*TILE+13,p=prog();
 if(['guide','witness','side','shop'].includes(o.type)){const role=['guide','witness','side','shop'].indexOf(o.type),look=role===3?3:NPC_LOOKS[state.chapter][role];if(!drawAtlas(g,'chars',look,x-11,y-31,22,34))npcSprite(g,x,y,role,time);let done=o.type==='guide'?p.guide:o.type==='witness'?p.witness:o.type==='side'?p.side:false;let mark=o.type==='side'?'✦':o.type==='shop'?'◎':done?'·':'!';pixelText(g,mark,x,y-40+Math.sin(time/300),o.type==='side'?'#a4dcea':o.type==='shop'?'#d4b982':'#fbe3a0',10);}
 else if(o.type==='camp'){if(drawAtlas(g,'props',10,x-13,y-22,26,26))return;rect(g,'#333e3b',x-10,y-2,20,6);rect(g,'#b4a58a',x-8,y+2,5,3);rect(g,'#b4a58a',x+5,y+2,5,3);for(let i=0;i<4;i++){let h=5+(Math.sin(time/130+i*2)*3|0);rect(g,'#d29b61',x-5+i*3,y-h,3,h+2);rect(g,'#f6d58b',x-2+i,y-h+2,2,h-1);}g.globalAlpha=.09;g.fillStyle='#ffc37b';g.beginPath();g.arc(x,y-4,28,0,Math.PI*2);g.fill();g.globalAlpha=1;}
 else if(o.type==='chest'){if(drawAtlas(g,'props',12,x-11,y-16,22,19,p.relic?.5:1)){if(!p.relic)pixelText(g,'◇',x,y-24,'#f3dbaa',12);return;}rect(g,'#29404a',x-11,y-4,23,9);rect(g,'#5d5549',x-9,y-9,19,12);rect(g,p.relic?'#4a4943':'#c3955c',x-8,y-13,17,p.relic?4:9);rect(g,'#e5c68c',x-9,y-6,19,2);rect(g,'#f6db99',x-1,y-7,3,5);if(!p.relic){pixelText(g,'◇',x,y-24,'#f3dbaa',12);}}
 else if(o.type==='boss'){let pulse=.4+.2*Math.sin(time/250);g.strokeStyle=`rgba(244,144,138,${pulse})`;g.beginPath();g.ellipse(x,y,18,7,0,0,Math.PI*2);g.stroke();if(!drawAtlas(g,'chars',BOSS_LOOKS[state.chapter],x-17,y-41,34,45))monster(g,2,x,y,1.7,1,state.chapter);pixelText(g,'首领',x,y-48,'#efb2a2',8);}
 else if(o.type==='gate'){if(p.resolved&&drawAtlas(g,'props',13,x-14,y-36,28,40)){pixelText(g,state.chapter===7?'写下明天':'下一程',x,y-43,'#f3d9a0',8);return;}rect(g,'#6b6050',x-1,y-19,3,23);rect(g,p.resolved?'#dfc88b':'#817b67',x-10,y-23,20,9);pixelText(g,'→',x,y-18,'#263641',10);if(p.resolved)pixelText(g,'下一程',x,y-33,'#f3d9a0',8);}
 else if(o.type==='inquiry'){drawAtlas(g,'props',14,x-12,y-31,24,35);pixelText(g,p.reflected?'◇':'◎',x,y-40,'#addef0',12);}
 else if(o.type==='sign'){rect(g,'#6b6251',x,y-14,2,18);rect(g,'#c8b18c',x-7,y-18,17,8);pixelText(g,'?',x+1,y-13,'#354348',8);}
 else if(o.type==='enemy'){monster(g,o.id%2,x,y+Math.sin(time/200+o.id),1.3,1,state.chapter);pixelText(g,'◆',x,y-22,'#c9867f',7);}
}
function drawWorld(time){if(!map)return;if(!map.base)bakeMap();camera.x=clamp(state.pos.x*TILE-W/2+8,0,MW*TILE-W);camera.y=clamp(state.pos.y*TILE-H/2+8,0,MH*TILE-H);ctx.imageSmoothingEnabled=false;ctx.fillStyle=map.theme.edge;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-Math.floor(camera.x),-Math.floor(camera.y));ctx.drawImage(map.base,0,0,MW*TILE,MH*TILE);
 for(let y=2;y<MH-2;y++)for(let x=2;x<MW-2;x++)if(map.tiles[y][x]===2&&map.seed(x,y)>.5)rect(ctx,'#c7e7db22',x*TILE+((time/200+x)%8),y*TILE+9,6,1);
 if(path.length){for(let [i,p]of path.entries())if(i%2===0)rect(ctx,'#f5d29555',p.x*TILE+7,p.y*TILE+7,2,2);}
 const objects=entities().map(o=>({y:o.y*TILE+13,draw:()=>drawObject(ctx,o,time)}));for(let y=0;y<MH;y++)for(let x=0;x<MW;x++)if(map.tiles[y][x]===3&&(x%2===0||y%2===0))objects.push({y:y*TILE+14,draw:()=>drawTree(ctx,x*TILE+8,y*TILE+15,map.theme)});
 const px=state.pos.x*TILE+8,py=state.pos.y*TILE+14;for(let i=partySize()-1;i>=1;i--){const ax=state.pos.x-(i*.65),ay=state.pos.y+i*.6;if(walkable(Math.round(ax),Math.round(ay)))objects.push({y:ay*TILE+13,draw:()=>hero(ctx,ax*TILE+8,ay*TILE+13,i,moving,time,25)});}
 objects.push({y:py,draw:()=>{ctx.strokeStyle='#efc58d88';ctx.beginPath();ctx.ellipse(px,py,8,3,0,0,Math.PI*2);ctx.stroke();hero(ctx,px,py,0,moving,time,29);}});objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());
 if(near){const x=near.x*TILE+8,y=near.y*TILE-24;pixelText(ctx,near.name,x,y,'#f6e4ba',7);}
 ctx.restore();for(let i=0;i<17;i++){const x=(i*97+Math.sin(time/1900+i)*13)%W,y=(i*41+time/(state.chapter===5?65:170))%H;rect(ctx,state.chapter===5?'#dfedf077':'#f4d49566',x,y,1,state.chapter===5?2:1);}
 drawMiniMap();
}
function drawMiniMap(){const x=W-76,y=9;rect(ctx,'#0d212bdc',x-4,y-4,73,48);for(let yy=0;yy<MH;yy+=2)for(let xx=0;xx<MW;xx+=2){let tile=map.tiles[yy][xx];rect(ctx,tile===2?'#3e6270':tile===3?'#203b40':tile===1?'#778473':'#35534f',x+xx*1.5,y+yy*1.5,3,3);}for(let o of entities().filter(o=>o.type!=='enemy'))rect(ctx,o.type==='boss'?'#d6948c':o.type==='side'||o.type==='inquiry'?'#a6d0e3':'#dbbf83',x+o.x*1.5,y+o.y*1.5,2,2);rect(ctx,'#fff5c4',x+state.pos.x*1.5-1,y+state.pos.y*1.5-1,3,3);}
function drawBattle(time){if(!battle)return;ctx.fillStyle='#142634';ctx.fillRect(0,0,W,H);if(landscape.complete&&landscape.naturalWidth){ctx.drawImage(landscape,0,100,landscape.naturalWidth,landscape.naturalHeight-100,0,0,W,H);rect(ctx,'#101e36aa',0,0,W,H);}else{rect(ctx,map.theme.grass,0,0,W,H);}rect(ctx,map.theme.grass+'bb',0,H*.5,W,H*.5);for(let i=0;i<38;i++)rect(ctx,'#9aa98b16',(i*71)%W,H*.55+(i*29)%(H*.45),12+(i%5),1);
 ctx.strokeStyle='#b2a48122';ctx.beginPath();ctx.ellipse(W*.5,H*.79,W*.4,H*.15,0,0,Math.PI*2);ctx.stroke();
 for(let i=0;i<partySize();i++){const p=allyPoint(i),h=state.heroes[i];let active=battle.actor===i&&!actionLock;ctx.strokeStyle=active?'#f4d595':'#93b3b333';ctx.beginPath();ctx.ellipse(p.x,p.y,W*.04,4,0,0,Math.PI*2);ctx.stroke();hero(ctx,p.x,p.y,i,false,time,W<400?39:47,h.hp<=0?5:fx?.actor===i?7:0,h.hp>0?1:.4);if(battle.shield[i]){ctx.strokeStyle='#b9dddf88';ctx.beginPath();ctx.ellipse(p.x,p.y-20,24,32,0,0,Math.PI*2);ctx.stroke();}pixelText(ctx,STORY.cast[i].name,p.x,p.y+11,h.hp>0?'#ded5c1':'#85949a',8);}
 battle.enemies.forEach((e,i)=>{if(e.hp<=0)return;const p=enemyPoint(i),size=battle.boss?(W<400?3.8:4.6):(W<400?2.3:3);rect(ctx,'#0b142955',p.x-size*7,p.y-2,size*14,5);if(battle.boss&&atlasCells.chars.length)drawAtlas(ctx,'chars',BOSS_LOOKS[state.chapter],p.x-size*9,p.y-size*23+Math.sin(time/350)*2,size*18,size*24);else monster(ctx,e.kind,p.x,p.y+Math.sin(time/300+i)*2,size,1,state.chapter);const by=p.y-(battle.boss?size*24:size*13)-15,bw=battle.boss?100:70;pixelText(ctx,e.name,p.x,by,'#e7ddcc',battle.boss?10:8);rect(ctx,'#233842',p.x-bw/2,by+10,bw,4);rect(ctx,e.charging?'#e9b77c':'#bf848d',p.x-bw/2,by+10,bw*e.hp/e.max,4);for(let j=0;j<3;j++)rect(ctx,j<e.break?'#edd99c':'#667581',p.x-9+j*7,by+19,4,2);if(e.stun)pixelText(ctx,'失衡',p.x,by-12,'#bce5cb',9);if(e.charging)pixelText(ctx,'⚠ 蓄力 · 魔法可打断',p.x,by-12,'#f5bd8c',8);if(i===battle.target&&!actionLock)pixelText(ctx,'▼',p.x,p.y+15,'#f7d598',9);});
 if(fx)drawFX(time);
}
function drawFX(time){let q=clamp((time-fx.start)/fx.duration,0,1),kind=fx.kind,from=allyPoint(Math.max(0,fx.actor)),target=enemyPoint(fx.targets[0]||0);ctx.save();const alpha=Math.sin(q*Math.PI);if(!reducedMotion&&['nova','ultimate','enemyNova'].includes(kind)&&q>.35&&q<.7)ctx.translate(Math.sin(time*1.3)*2,Math.cos(time)*2);
 if(kind==='heal'||kind==='shield'){for(let i=0;i<partySize();i++){let p=allyPoint(i);ctx.strokeStyle='#afefcf';ctx.globalAlpha=alpha;ctx.beginPath();ctx.ellipse(p.x,p.y-10-q*18,18+q*8,7,0,0,Math.PI*2);ctx.stroke();for(let j=0;j<12;j++){let x=p.x+Math.cos(j*2.1+q*3)*21,y=p.y-((j*7+q*75)%65);rect(ctx,j%2?'#f8efc7':'#94decb',x,y,2,3);}}}
 else if(kind==='charge'){ctx.globalAlpha=alpha;for(let j=0;j<32;j++){let a=j*Math.PI/16+q*3,r=70*(1-q);rect(ctx,'#f6bc9f',target.x+Math.cos(a)*r,target.y-30+Math.sin(a)*r,2,2);}}
 else if(kind==='enemy'||kind==='enemyNova'){ctx.globalAlpha=alpha;const p=allyPoint((battle.round+fx.targets[0])%partySize());ctx.strokeStyle='#f0a6ae';ctx.lineWidth=kind==='enemyNova'?3:2;ctx.beginPath();ctx.moveTo(target.x,target.y-20);ctx.lineTo(p.x,p.y-25);ctx.stroke();if(kind==='enemyNova'){ctx.fillStyle='#ce657022';ctx.fillRect(0,0,W,H);for(let i=0;i<3;i++){let a=allyPoint(i);ctx.beginPath();ctx.arc(a.x,a.y-20,q*50,0,Math.PI*2);ctx.stroke();}}}
 else if(kind==='attack'||kind==='slash'){ctx.globalAlpha=alpha;ctx.strokeStyle=kind==='slash'?'#ddd7ff':'#fff1c7';ctx.lineWidth=kind==='slash'?4:2;ctx.beginPath();ctx.moveTo(target.x-25+q*10,target.y-60);ctx.lineTo(target.x+25-q*10,target.y+3);ctx.stroke();ctx.strokeStyle='#a6c7e0';ctx.lineWidth=1;ctx.beginPath();ctx.arc(target.x,target.y-25,38,q*5,q*5+2.4);ctx.stroke();}
 else if(kind==='clone'){ctx.globalAlpha=alpha;for(let j=0;j<3;j++){if(fx.actor===0&&spriteReady){ctx.save();ctx.globalAlpha=.35*alpha;ctx.drawImage(sprite,(Math.floor(q*7)%8)*192,2*208,192,208,target.x-58+j*34,target.y-62+Math.sin(j+q*6)*18,38,44);ctx.restore();}else hero(ctx,target.x-42+j*34,target.y-15+Math.sin(j+q*6)*22,fx.actor,false,time,42,7,.35);ctx.strokeStyle='#efdbff';ctx.beginPath();ctx.moveTo(target.x-30+j*7,target.y-50+j*15);ctx.lineTo(target.x+35-j*5,target.y-10+j*9);ctx.stroke();}}
 else if(kind==='meteor'||kind==='shards'){ctx.globalAlpha=alpha;for(let j=0;j<24;j++){let x=W*.35+(j*43)%Math.round(W*.6),y=((q*H*2+j*23)%(H+80))-70;rect(ctx,j%3?'#c3e5ee':'#f9dbad',x,y,kind==='shards'?2:3,9);rect(ctx,'#ffffff',x,y+9,3,3);}}
 else if(kind==='nova'||kind==='ultimate'){let big=kind==='ultimate';rect(ctx,big?'#1a163cc9':'#16335399',0,0,W,H);const center={x:W*.62,y:H*.47};ctx.globalAlpha=alpha;for(let r=0;r<4;r++){ctx.strokeStyle=r%2?'#f4d5a0':'#b9dbe8';ctx.lineWidth=r%2?1:2;ctx.beginPath();ctx.arc(center.x,center.y,18+r*20+Math.sin(q*Math.PI)*15,0,Math.PI*2);ctx.stroke();}for(let j=0;j<12;j++){let a=j*Math.PI/6+q*3,r=big?95:68;ctx.strokeStyle=j%2?'#c8b3e4':'#a5d9dc';ctx.beginPath();ctx.moveTo(center.x+Math.cos(a)*r,center.y+Math.sin(a)*r);ctx.lineTo(center.x+Math.cos(a+2)*r,center.y+Math.sin(a+2)*r);ctx.stroke();}if(big)for(let i=0;i<3;i++){let p=allyPoint(i);ctx.strokeStyle=['#edcd98','#bbecd6','#cdb9f5'][i];ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p.x,p.y-20);ctx.lineTo(center.x,center.y);ctx.stroke();}for(let i=0;i<55;i++){let a=i*2.4+fx.seed,r=q*(big?230:170);rect(ctx,i%3?'#d7e9dd':'#ffd894',center.x+Math.cos(a)*r,center.y+Math.sin(a)*r,2+i%2,2+i%2);}if(q>.55&&q<.68)rect(ctx,'#fff3d344',0,0,W,H);}
 else{let x=from.x+(target.x-from.x)*Math.min(1,q*1.6),y=from.y-25+(target.y-from.y)*Math.min(1,q*1.6),r=8+Math.sin(q*Math.PI)*14;ctx.globalAlpha=alpha;for(let j=0;j<4;j++){ctx.strokeStyle=j%2?'#d4eced':'#96c2d6';ctx.beginPath();ctx.arc(x,y,r+j*3,q*12+j,q*12+j+4);ctx.stroke();}for(let j=0;j<20;j++){let a=j*2.4+q*8;rect(ctx,'#f1e6c0',x+Math.cos(a)*r*1.7,y+Math.sin(a)*r*1.3,2,2);}}
 ctx.restore();
}
function resizeCanvas(){if($('playScreen').hidden)return;const r=$('viewport').getBoundingClientRect();W=r.width<480?240:r.width<850?360:480;H=Math.round(W*r.height/r.width);canvas.width=W*2;canvas.height=H*2;ctx.setTransform(2,0,0,2,0,0);ctx.imageSmoothingEnabled=false;}
function update(dt,time){if(!state)return;if(mode!=='title'&&$('modalShade').hidden)state.playSeconds+=dt;if(mode==='dialogue'&&dialogue){if(dialogue.typed<dialogue.fullText.length){const n=Math.min(dialogue.fullText.length,Math.floor((time-dialogue.start)/18));if(n!==dialogue.typed){dialogue.typed=n;$('dialogueText').textContent=dialogue.fullText.slice(0,n);}if(n===dialogue.fullText.length)showChoicesIfNeeded();}return;}if(mode!=='world'||!$('modalShade').hidden){moving=false;return;}
 let dx=(keys.right?1:0)-(keys.left?1:0),dy=(keys.down?1:0)-(keys.up?1:0);moving=false;const speed=4.3;
 if(dx||dy){path=[];const mag=Math.hypot(dx,dy);dx/=mag;dy/=mag;let nx=clamp(state.pos.x+dx*speed*dt,1,MW-2),ny=clamp(state.pos.y+dy*speed*dt,1,MH-2);if(walkable(Math.round(nx),Math.round(state.pos.y))){state.pos.x=nx;moving=true;}if(walkable(Math.round(state.pos.x),Math.round(ny))){state.pos.y=ny;moving=true;}if(dx)state.facing=dx<0?'left':'right';}
 else if(path.length){const target=path[0],dist=Math.hypot(target.x-state.pos.x,target.y-state.pos.y),step=speed*dt;if(dist<=step){state.pos={x:target.x,y:target.y};path.shift();if(!path.length&&path.target){const o=path.target;path=[];interact(o);return;}}else{state.facing=target.x<state.pos.x?'left':'right';state.pos.x+=(target.x-state.pos.x)/dist*step;state.pos.y+=(target.y-state.pos.y)/dist*step;}moving=true;}
 let nearest=null,min=1.9;for(let o of entities()){let d=Math.hypot(o.x-state.pos.x,o.y-state.pos.y);if(d<min){nearest=o;min=d;}}near=nearest;const hint=near?('E / A · '+objectiveLabel(near)+' '+near.name):'';if(hint!==lastHint){lastHint=hint;$('interactHint').textContent=hint;$('interactHint').hidden=!hint;}
 if(near?.type==='enemy'&&min<.58){interact(near);return;}
 if(moving&&time-lastSaved>2500)save();
}
function loop(time){let dt=lastTime?Math.min(.06,(time-lastTime)/1000):0;lastTime=time;update(dt,time);if(state&&mode!=='title'){if(battle)drawBattle(time);else drawWorld(time);}requestAnimationFrame(loop);}
$('newBtn').onclick=()=>{Audio.init();const old=loadStored();if(old){openModal('开始新的旅程','A NEW BEGINNING');$('modalBody').innerHTML='<p>新旅程会替换此浏览器的当前存档。已有存档可以先导出保存。</p>';let exportBtn=document.createElement('button');exportBtn.className='button secondary';exportBtn.textContent='先导出旧存档';exportBtn.onclick=()=>download('灰烬之名-旧存档.json',JSON.stringify(old,null,2),'application/json');$('modalBody').append(exportBtn);let start=document.createElement('button');start.className='button primary';start.textContent='确认开始新旅程';start.onclick=()=>startGame(newState(),true);$('modalBody').append(start);}else startGame(newState(),true);};
$('continueBtn').onclick=()=>{const s=loadStored();if(s)startGame(s);else toast('没有可读取的存档，请开始新旅程。');};
$('nextDialogue').onclick=advanceDialogue;$('skipDialogue').onclick=skipDialogue;$('dialogueText').onclick=typeFull;
$('journalBtn').onclick=()=>openJournal();$('menuBtn').onclick=()=>openJournal();$('helpBtn').onclick=openHelp;$('titleHelp').onclick=openHelp;$('saveBtn').onclick=openSave;$('restBtn').onclick=rest;$('closeModal').onclick=closeModal;$('soundBtn').onclick=()=>Audio.toggle();
$('fullBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('此浏览器不支持全屏，可横屏游玩或添加到主屏幕。');}catch{toast('全屏未开启，可继续在当前画面游玩。');}};
$('fieldMessage').onclick=()=>{if(mode!=='world')return;const p=prog(),type=p.resolved&&p.reflected?'gate':!p.guide?'guide':!p.witness?'witness':!p.relic?'chest':!p.reflected?'inquiry':p.kills<2?'enemy':'boss';const o=entities().find(o=>o.type===type);if(o)targetObject(o);};
$('interactBtn').onclick=()=>{Audio.init();interact();};
$('modalShade').addEventListener('click',e=>{if(e.target===$('modalShade'))closeModal();});
$('importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>200000){toast('文件过大，这不是有效的游戏存档。');return;}try{const imported=validateSave(JSON.parse(await file.text()));openModal('导入这段旅程','RESTORE YOUR JOURNEY');$('modalBody').innerHTML='<p>第 '+(imported.chapter+1)+' 章 · '+STORY.chapters[imported.chapter].place+' · Lv.'+imported.level+'</p><p>将替换当前浏览器存档。请确认这是要继续的旅程。</p>';let b=document.createElement('button');b.className='button primary';b.textContent='确认导入并继续';b.onclick=()=>{startGame(imported);toast('存档已导入');};$('modalBody').append(b);}catch{toast('无法读取存档：文件损坏或版本不兼容。现有进度未变更。');}};
const keyDirs={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'};
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(! $('modalShade').hidden){if(e.key==='Escape'){closeModal();e.preventDefault();}if(e.key==='Tab'){const all=[...$('modal').querySelectorAll('button:not(:disabled),a[href],input')].filter(el=>el.getClientRects().length);if(all.length){const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}return;}
 if(mode==='title')return;if(keyDirs[e.key]){e.preventDefault();keys[keyDirs[e.key]]=true;}
 if(['e','E',' ','Enter'].includes(e.key)&&!e.repeat){if(e.target.tagName==='BUTTON'&&mode==='battle')return;e.preventDefault();interact();}
 if(['j','J','Escape'].includes(e.key)&&!e.repeat){e.preventDefault();if(mode!=='dialogue')openJournal();}
});
window.addEventListener('keyup',e=>{if(keyDirs[e.key])keys[keyDirs[e.key]]=false;});window.addEventListener('blur',()=>{keys={};});document.addEventListener('visibilitychange',()=>{keys={};if(document.hidden&&state&&mode==='world')save();lastTime=0;});window.addEventListener('pagehide',()=>{if(state&&mode==='world')save();});
for(let btn of document.querySelectorAll('[data-dir]')){btn.addEventListener('pointerdown',e=>{e.preventDefault();Audio.init();keys[btn.dataset.dir]=true;btn.setPointerCapture(e.pointerId);});const release=()=>keys[btn.dataset.dir]=false;btn.addEventListener('pointerup',release);btn.addEventListener('pointercancel',release);btn.addEventListener('lostpointercapture',release);}
canvas.addEventListener('pointerdown',e=>{if(mode==='dialogue'){advanceDialogue();return;}if(mode!=='world'||!$('modalShade').hidden)return;Audio.init();let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W+camera.x,y=(e.clientY-r.top)/r.height*H+camera.y;const tx=Math.floor(x/TILE),ty=Math.floor(y/TILE);let o=entities().find(o=>Math.abs(o.x-tx)<1.1&&Math.abs(o.y-ty)<1.4);if(o)targetObject(o);else path=findPath(tx,ty);});
window.addEventListener('resize',resizeCanvas);new ResizeObserver(resizeCanvas).observe($('viewport'));
// These tools use the very same navigation and interaction paths as touch and keyboard.
const inspect=()=>state?{mode,chapter:state.chapter,place:ch().place,level:state.level,pos:{...state.pos},progress:{...prog()},memories:state.progress.filter(p=>p.side).length,party:state.heroes.slice(0,partySize()).map((h,i)=>({name:STORY.cast[i].name,hp:h.hp,mp:h.mp,maxHp:stats(i).hp,maxMp:stats(i).mp,atk:stats(i).atk,def:stats(i).def})),near:near?{type:near.type,name:near.name}:null,battle:battle?{round:battle.round,actor:battle.actor,target:battle.target,enemies:battle.enemies.map(e=>({...e}))}:null}: {mode:'title'};
window.AshGame={inspect,worldObjects:()=>map?entities().map(o=>({...o})):[],navigateTo:(x,y)=>{if(!Number.isInteger(x)||!Number.isInteger(y)||!walkable(x,y)||mode!=='world')throw Error('目的地不可行走');path=findPath(x,y);return {steps:path.length};},interactNearby:()=>{if(mode!=='world'||!near)throw Error('附近没有可互动的目标');interact();return inspect();}};
try{const mc=document.modelContext;if(mc?.registerTool){Promise.resolve(mc.registerTool({name:'read_ash_names_game',description:'Read current chapter, party, nearby interaction and combat state without changing progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('No arguments expected');return inspect();}})).catch(()=>{});}}catch{/* Browsers without WebMCP still run the full game. */}
showTitle();requestAnimationFrame(loop);
})();
