const vm=require('vm'),fs=require('fs'),assert=require('assert');
const path=require('path');
const root=path.resolve(__dirname,'..')+'/';
const output=path.join(__dirname,'.generated');fs.mkdirSync(output,{recursive:true});
function createEnv(){
 const timers=new Map();let tid=0;const context2d=new Proxy({measureText:t=>({width:t.length*7})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
 class Element{constructor(id=''){this.id=id;this.hidden=false;this.children=[];this.style={};this.disabled=false;this.attrs={};this.tagName='DIV';this._html='';this.textContent='';this.files=[];this.classList={toggle(){},add(){},remove(){}};}set innerHTML(v){this._html=v;this.children=[];}get innerHTML(){return this._html;}append(e){this.children.push(e);}remove(){}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k];}addEventListener(){}focus(){}click(){if(!this.disabled)this.onclick?.({target:this});}getContext(){return context2d;}getBoundingClientRect(){return {width:960,height:576,x:0,y:0,left:0,top:0};}getClientRects(){return[1];}toDataURL(){return 'data:image/png;base64,';}querySelector(){return this.children[0]||new Element();}querySelectorAll(){return this.children;}setPointerCapture(){}}
 const elements=new Map(),doc={getElementById(id){if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);},createElement:tag=>{let e=new Element();e.tagName=tag.toUpperCase();return e;},querySelectorAll:()=>[],addEventListener(){},hidden:false,documentElement:new Element(),activeElement:new Element()};
 for(let id of ['modalShade','playScreen','dialogue'])doc.getElementById(id).hidden=true;
 const mem=new Map(),errors=[];const c={document:doc,console:{log:console.log,warn:console.warn,error:(...a)=>errors.push(a.map(String).join(' '))},performance:{now:()=>Date.now()},Date,Math:Object.create(Math),Map,Set,Blob,URL,structuredClone,Error,JSON,Object,Number,Array,String,Promise,Uint8Array,localStorage:{getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v)},Image:class{set src(v){}},ResizeObserver:class{observe(){}},matchMedia:()=>({matches:true}),requestAnimationFrame:()=>{},setTimeout:(fn,ms)=>{if(ms<=1800)queueMicrotask(fn);return ++tid;},clearTimeout(){},setInterval(){},clearInterval(){},addEventListener(){}};c.window=c;c.Math.random=()=>.5;vm.createContext(c);vm.runInContext(fs.readFileSync(root+'story.js','utf8'),c);vm.runInContext(fs.readFileSync(root+'philosophy.js','utf8'),c);vm.runInContext(fs.readFileSync(root+'ai-cases.js','utf8'),c);let source=fs.readFileSync(root+'game.js','utf8');source=source.replace(/\}\)\(\);\s*$/,`globalThis.TEST={startGame,newState,createMap,findPath,walkable,interact,skipDialogue,advanceDialogue,typeFull,act,startBattle,renderBattle,drawWorld,drawBattle,validateSave,save,loadStored,travel,rest,openHelp,openSave,openJournal,playEnding,renderHUD,update,stats,showChoicesIfNeeded,closeModal,chooseEnding,get state(){return state},get map(){return map},get dialogue(){return dialogue},get battle(){return battle},get mode(){return mode},get actionLock(){return actionLock},get SKILLS(){return SKILLS}};})();`);vm.runInContext(source,c);return {c,t:c.TEST,doc,errors,mem};
}
const e=createEnv(),{t,doc,c}=e;let checks=[];
function report(s){checks.push(s);console.log('PASS '+s);}
function settle(choice=0){let guard=0;while(t.dialogue&&guard++<20){if(t.dialogue.choices){t.typeFull();doc.getElementById('dialogueChoices').children[choice].click();}else t.skipDialogue();}assert(guard<20);}
function contact(type,id){let o=[...t.map.objects,...t.map.mobs].find(o=>o.type===type&&(id===undefined||o.id===id));assert(o,'missing '+type);t.state.pos={x:o.x,y:o.y};t.interact(o);}
(async()=>{
 t.startGame(t.newState(),true);assert.equal(t.mode,'dialogue');settle();assert.equal(t.mode,'world');report('new game, opening dialogue, save and HUD initialize');
 for(let k=0;k<8;k++){t.state.unlocked=7;t.state.chapter=k;t.travel(k);for(let o of [...t.map.objects,...t.map.mobs]){const p=t.findPath(o.x,o.y);assert(p.length||Math.round(t.state.pos.x)===o.x&&Math.round(t.state.pos.y)===o.y,'unreachable '+k+' '+o.type);for(let step of p)assert(t.walkable(step.x,step.y));}t.drawWorld(200);report('chapter '+(k+1)+' all NPCs, relic, enemies and exit reachable');}
 t.startGame(t.newState(),true);settle();contact('witness');settle();assert.equal(t.state.progress[0].witness,false);contact('chest');settle();assert.equal(t.state.progress[0].relic,false);contact('boss');settle();assert.equal(t.mode,'world');report('chapter gates reject out-of-order witness, chest and boss');
 const chapterResults=[];
 async function fight(){let n=0;while(t.battle&&n++<120){const battle=t.battle;assert.equal(t.mode,'battle');let actor=battle.actor,s=t.stats(actor),h=t.state.heroes[actor],low=t.state.heroes.slice(0,t.state.unlocked?3:2).some((h,i)=>h.hp<t.stats(i).hp*.4),skill=t.SKILLS[actor].filter(v=>v.lv<=t.state.level&&v.cost<=h.mp&&!v.shield&&!v.revive&&!v.heal).at(-1),id=low&&actor===1&&h.mp>=8?'heal':low&&t.state.potions?'potion':t.state.limit>=100&&t.state.unlocked>=1&&t.state.heroes.every(h=>h.hp>0)?'ultimate':skill?.id||'attack';await t.act(id);t.drawBattle(350);assert(!e.errors.length,e.errors.join('\n'));}assert(n<120,'battle stuck');settle(0);}
 for(let k=0;k<8;k++){
 assert.equal(t.state.chapter,k);contact('guide');settle();contact('witness');settle();contact('side');settle();contact('chest');settle();contact('inquiry');settle();assert(t.state.progress[k].reflected);assert(t.state.progress[k].inquiryChoices.length===2);assert(t.state.progress[k].relic);assert(t.state.progress[k].side);contact('enemy',0);await fight();contact('enemy',1);await fight();assert(t.state.progress[k].kills>=2);contact('camp');settle();contact('boss');settle();await fight();assert(t.state.progress[k].boss,'boss not defeated '+k);assert(t.state.progress[k].resolved,'chapter unresolved '+k);chapterResults.push({chapter:k+1,level:t.state.level,gold:t.state.gold,mp:t.state.heroes.map(h=>h.mp)});if(k<7){contact('gate');settle();}
 }
 report('eight chapters completed through actual dialogue, combat, rewards and travel logic');
 assert(t.state.endings.includes('ember'));t.playEnding('sea');settle();assert(t.state.endings.includes('sea'));t.playEnding('dawn');settle();assert(t.state.endings.includes('dawn')&&t.state.endings.includes('names'));report('three endings and all-eight-memories hidden epilogue');
 t.closeModal();t.save();let saved=t.loadStored();assert(saved&&saved.chapter===7&&saved.progress.every(p=>p.boss));assert.throws(()=>t.validateSave({...saved,chapter:9}));assert.throws(()=>t.validateSave({...saved,heroes:[]}));assert.throws(()=>t.validateSave({...saved,progress:[]}));assert.throws(()=>t.validateSave({...saved,gold:NaN}));report('save round-trip and corrupted-save rejection');
 const legacy=structuredClone(saved);legacy.version=1;legacy.progress.forEach(p=>{delete p.reflected;delete p.inquiryChoices;});assert.equal(t.validateSave(legacy).version,2);const broken=structuredClone(saved);broken.progress[0].inquiryChoices=[99,0];assert.throws(()=>t.validateSave(broken));assert.equal(c.PHILOSOPHY.chapters.flatMap(x=>x.cards).length,32);assert.equal(c.AI_CASES.length,8);report('legacy migration, invalid inquiry choices rejected and 32 concepts bound');
 for(let k=0;k<8;k++){t.travel(k);contact('inquiry');settle(1);assert.deepEqual(Array.from(t.state.progress[k].inquiryChoices),[1,1]);for(let tab of ['quests','bag','skills','memories','concepts','cases','map','people']){t.openJournal(tab);t.closeModal();}}report('alternate decisions across all eight AI cases and every journal tab');
 t.travel(0);assert.equal(t.state.chapter,0);assert.equal(t.state.unlocked,7);assert(t.state.progress[0].boss);t.travel(7);assert.equal(t.state.chapter,7);report('return travel retains all chapter progress and collectibles');
 t.state.progress[7].side=false;t.state.progress[6].side=false;t.state.progress[5].side=false;t.state.progress[4].side=false;t.state.progress[3].side=false;t.chooseEnding();t.typeFull();assert(doc.getElementById('dialogueChoices').children[2].disabled);doc.getElementById('dialogueChoices').children[3].click();report('fewer than four memories locks shared-dawn ending');
 t.startBattle(false,3);t.state.heroes.forEach(h=>h.hp=1);t.battle.actor=0;t.state.heroes[0].mp=0;await t.act('guard');t.state.heroes[1].mp=0;await t.act('guard');t.state.heroes[2].mp=0;await t.act('guard');assert(!e.errors.length);report('defense, enemy phase and depleted magic remain actionable');
 t.battle.enemies.forEach(v=>v.hp=10000);t.state.heroes.forEach(h=>h.hp=1);await t.act('attack');await t.act('attack');await t.act('attack');if(t.dialogue)settle();assert(t.state.heroes.some(h=>h.hp>0));report('party defeat returns safely without losing progress');
 t.closeModal();t.openHelp();t.closeModal();t.openSave();t.closeModal();assert(!e.errors.length,e.errors.join('\n'));report('help and save panels open without runtime errors');
 fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,chapterResults,errors:e.errors},null,2));fs.writeFileSync(path.join(output,'test-save.json'),JSON.stringify(saved,null,2));console.log('RESULT '+JSON.stringify({checks:checks.length,chapterResults,errors:e.errors}));
})().catch(err=>{console.error(err);process.exit(1);});
