const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'..');
class Element{constructor(){this.children=[];this.hidden=true;this.textContent='';this.style={};this.dataset={};this.tagName='CANVAS';this.width=384;this.height=240;}append(...a){this.children.push(...a);}replaceChildren(...a){this.children=a;}getContext(){return new Proxy({},{get:()=>()=>{}});}getBoundingClientRect(){return {width:800,height:500,left:0,top:0};}querySelector(){return new Element();}querySelectorAll(){return [];}addEventListener(){}setAttribute(){}focus(){}click(){this.onclick?.();}}
const elements={},storage=new Map(),timers=[];const document={getElementById:id=>elements[id]??=new Element(),createElement:()=>new Element(),createTextNode:text=>({textContent:text}),querySelectorAll:()=>[],addEventListener(){},activeElement:new Element()};
const context={console,document,window:{addEventListener(){}},navigator:{},localStorage:{setItem:(k,v)=>storage.set(k,v),getItem:k=>storage.get(k)||null},ResizeObserver:class{observe(){}},requestAnimationFrame(){},setTimeout:f=>(timers.push(f),timers.length),clearTimeout(){},setInterval(){},performance:{now:()=>5000},Blob,URL,Image:class{},Art:{init:()=>Promise.resolve(),portrait(){},frames:[],propFrames:[]}};vm.createContext(context);
for(const f of ['story.js','philosophy.js','world.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);
const code=fs.readFileSync(path.join(root,'game.js'),'utf8').replace(/\}\)\(\);\s*$/,'globalThis.TEST={fresh,cleanSave,required,endingAllowed,checkpoint,rewind,hostEvent,interact,next,objective,goTo,advance,save,conditionalEcho,inspect,get state(){return state},set state(s){state=s},get dialog(){return dialog},get mode(){return mode},set mode(m){mode=m},get path(){return path}};})();');vm.runInContext(code,context);
const {WORLD:W,TALE:T,PHILOSOPHY:P,TEST:G}=context;const json=o=>JSON.parse(JSON.stringify(o));let checks=0;function check(v,msg){assert(v,msg);checks++;}function finishDialog(){let guard=0;while(G.dialog&&!G.dialog.options){G.next();if(++guard>100)throw Error('Dialogue loop');}}function choose(i){check(!!G.dialog?.options,'Choice exists');G.dialog.options[i].action();finishDialog();}function settle(){while(timers.length)timers.shift()();}
check(T.cases.length===8,'eight cases');check(T.endings.length===6,'six endings');check(P.chapters.flatMap(c=>c.cards).length===32,'32 concept groups');check(Object.keys(W.maps).length>=35,'nested maps');
const full=G.fresh();full.chapter=8;full.flags.archiveDoor=true;full.records.forEach(r=>Object.assign(r,{started:true,route:0,decision:0,completed:true}));
for(const m of Object.values(W.maps)){
 check(W.passable(m,m.start.x,m.start.y),'spawn '+m.id);
 for(const o of m.objects){const targets=o.type==='portal'?[o]:[[0,1],[0,-1],[1,0],[-1,0]].map(([dx,dy])=>({x:o.x+dx,y:o.y+dy}));check(targets.some(t=>W.passable(m,t.x,t.y)&&(W.findPath(m,m.start,t).length||t.x===m.start.x&&t.y===m.start.y)),'reachable '+m.id+' / '+o.id);if(o.type==='portal'){check(W.passable(W.maps[o.dest],o.spawn.x,o.spawn.y),'return spawn '+m.id+' -> '+o.dest);check(W.mapRoute(m.id,o.dest,full)?.length>0,'route '+m.id+' -> '+o.dest);}else check(!W.passable(m,o.x,o.y),'object collision '+o.id);}
}
for(let route=0;route<2;route++)for(let decision=0;decision<3;decision++){
 G.state=G.fresh();G.mode='world';elements.modalShade.hidden=true;
 for(let i=0;i<8;i++){
  const c=T.cases[i];G.state.map=c.hostMap;G.state.pos={...W.maps[c.hostMap].start};G.hostEvent();choose(route);check(G.state.records[i].route===route,'route saved');check(G.required().length===3,'three clues');check(G.state.checkpoints.length===i*2+1,'route checkpoint');
  for(const id of G.required()){const place=W.cluePlaces[id];check(W.mapRoute(G.state.map,place.map,G.state)!==null,'clue route '+id);G.state.map=place.map;G.interact(W.maps[place.map].objects.find(o=>o.id===id));finishDialog();}
  G.state.map=c.hostMap;G.state.pos={...W.maps[c.hostMap].start};G.hostEvent();choose(decision);check(G.state.chapter===i+1,'chapter progressed');check(G.state.checkpoints.length===(i+1)*2,'decision checkpoint');check(G.cleanSave(json(G.state)).chapter===i+1,'valid roundtrip');
 }
 check(G.endingAllowed(T.endings[0]),'baseline ending always available');G.state.sides=T.sides.map(s=>s.id);const before=json(G.state);G.state.endings=['normal'];G.rewind(4);check(G.state.chapter===2,'rewind chapter');check(G.state.clues.every(id=>T.clues[id].case<2),'rewind removes future clues');check(G.state.records.slice(2).every(r=>!r.completed&&!r.started),'rewind clears future choices');check(G.state.endings.includes('normal'),'ending collection preserved');G.state=before;
}
// Unlock predicates are consequences, not ontology scores.
G.state=G.fresh();G.state.records.forEach(r=>r.decision=0);G.state.records[6].decision=1;check(G.endingAllowed(T.endings.find(e=>e.id==='manual')),'manual trigger');G.state.records[0].decision=1;G.state.records[5].decision=0;check(G.endingAllowed(T.endings.find(e=>e.id==='holiday')),'holiday trigger');G.state.records[3].decision=2;check(G.endingAllowed(T.endings.find(e=>e.id==='elsewhere')),'leave trigger');G.state.records[6].decision=2;G.state.sides=T.sides.slice(0,4).map(s=>s.id);check(G.endingAllowed(T.endings.find(e=>e.id==='trial')),'trial trigger');
G.state=G.fresh();G.mode='world';G.state.map='archive';G.state.records[4]={started:true,route:1,completed:false,decision:null};G.state.chapter=4;G.state.clues.push('origin_clock');G.interact(W.maps.archive.objects.find(o=>o.puzzle));choose(0);check(!G.state.flags.archiveDoor,'wrong clock keeps door');G.interact(W.maps.archive.objects.find(o=>o.puzzle));choose(1);settle();check(G.state.map==='secret','clock opens separate secret map');
const invalid=G.fresh();invalid.pos.x=-100;assert.throws(()=>G.cleanSave(invalid));assert.throws(()=>G.cleanSave({version:2}));const future=G.fresh();future.clues=['stock_list'];assert.throws(()=>G.cleanSave(future));
G.mode='world';G.state.map='archive';G.state.chapter=5;G.state.records[4].route=0;G.state.flags.archiveDoor=false;G.interact(W.maps.archive.objects.find(o=>o.puzzle));choose(1);settle();check(G.state.map==='secret','completed case permits alternate secret route');
// Movement advances real frames while preserving grid collision.
G.state=G.fresh();G.mode='world';elements.modalShade.hidden=true;G.goTo(16,18);const seen=new Set();for(let n=0;n<35;n++){G.advance(.03,20000+n*30);seen.add(G.state.walkFrame);}check(seen.size===4,'all four walking frames');check(G.state.pos.y===18,'path reached');G.advance(.03,22000);check(G.state.walkFrame===1,'idle pose resets');
if(process.env.QA_SAVE_DIR){const dest=process.env.QA_SAVE_DIR;fs.mkdirSync(dest,{recursive:true});const s=G.fresh();s.chapter=8;s.map='isles';s.pos={x:24,y:22};s.known=Object.keys(W.maps);s.clues=Object.keys(T.clues);s.sides=T.sides.map(x=>x.id);s.flags.archiveDoor=true;s.records.forEach((r,i)=>Object.assign(r,{started:true,completed:true,route:1,decision:[2,0,2,2,0,0,2,0][i]}));G.cleanSave(s);fs.writeFileSync(path.join(dest,'all-cases.json'),JSON.stringify(s,null,2));}
console.log(JSON.stringify({status:'PASS',checks,maps:Object.keys(W.maps).length,cases:T.cases.length,routeResolutionCombinations:48,clues:Object.keys(T.clues).length,optionalStories:T.sides.length,endings:T.endings.length,conceptGroups:32}));
