const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'..'),ctx={};vm.createContext(ctx);for(const f of ['story.js','philosophy.js','world.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);const {TALE:t,PHILOSOPHY:p,WORLD:w}=ctx;
let beats=0;const lines=a=>{beats+=a.length;return a.map(([who,text])=>'**'+who+'**：'+text).join('\n\n')+'\n\n';};
const foundation='这是一个前魔法世界：人工智能突破后，物质编译技术让人们能够合成食物、改造物体、修复设施。居民把这些先进技术叫作魔法。物质充裕没有自动消除权力、依赖、丧失和生活的难题。\n\n本作以海德格尔的分析框架重问此在、技术与人工智能。三者不预先被当作同一类概念：此在关乎存在方式，技术关乎揭示与相处，AI 既是技术成果，也可能迫使我们重审谁能够具有此在的一切特征。技术机制、行为证据、第一人称叙述和伦理安排不会被直接当作彼此的证明。游戏没有此在认证、觉醒指数、本真积分或一个替所有人裁决的真结局。';
let md='# 明天照常营业 · 完整剧本\n\n'+t.premise+'\n\n八个案件、十六条调查路线、二十四个处置分支、八件闲事、六种结局与一段全收集尾声。下文包含完整剧透。\n\n## 世界与叙事\n\n'+foundation+'\n\n## 人物\n\n'+Object.values(t.people).map(p=>'**'+p.name+' · '+p.job+'**\n\n'+p.bio).join('\n\n')+'\n\n## 开场\n\n'+lines(t.opening);
for(const [i,c]of t.cases.entries()){
 md+='## 第 '+(i+1)+' 案 · '+c.title+'\n\n'+c.subtitle+'\n\n地点：'+c.place+'。\n\n### 开场与委托\n\n'+lines(c.brief)+'### 调查路线\n\n'+c.routeQuestion+'\n\n';
 c.routes.forEach((r,n)=>{md+='#### 路线 '+(n+1)+'：'+r.label+'\n\n'+lines(r.lines);const clue=t.clues[r.clue];md+='**线索：'+clue.title+'**\n\n'+lines(clue.lines);});
 md+='### 共同线索\n\n';for(const id of c.common){const clue=t.clues[id];md+='**'+clue.title+'**\n\n'+lines(clue.lines);}
 md+='### 回来商量\n\n'+lines(c.confrontation);c.decisions.forEach((d,n)=>md+='#### 处置 '+(n+1)+'：'+d.label+'\n\n'+lines(d.lines)+'留下的安排：'+d.after+'\n\n');md+='### 案件尾声\n\n'+lines(c.coda)+'接下来：'+c.lead+'\n\n本案延伸阅读：'+p.chapters[i].cards.map(x=>x.term).join('；')+'。\n\n';
}
md+='## 街边的八件闲事\n\n';for(const s of t.sides)md+='### '+s.title+'\n\n地点：'+w.maps[s.map].name+'。\n\n'+lines(s.lines);
for(const e of t.endings)md+='## 结局 · '+e.name+'\n\n'+e.subtitle+'\n\n出现条件：'+e.need+'。\n\n你的安排：'+e.choice+'。\n\n'+lines(e.lines);
md+='## 全收集尾声 · 洗碗\n\n任意结局时，如果已经发现八件闲事，就追加这一段。它不是高于其他结局的标准答案。\n\n'+lines(t.extra)+'## 分歧与地图的实际规则\n\n每案先与委托人交谈，在两条调查路线中选一条。两条共同线索与一条路线线索齐全后，回到委托人处选择三种处置之一。调查路线会打开不同房间；完成案件后可以重访另一条路线的地点。处置决定改变后续人物回应与最终可实施的方案。\n\n分歧页保留每案选路线前、作处置前的两个回溯点。回溯会撤回之后的线索与决定，已看结局保留在收藏中。选择空间是多条交叉分歧与重访路径，而不是宣称每一种组合都拥有完全独立的长篇剧情。\n\n'+Object.values(w.maps).map(m=>'- '+w.ancestors(m.id).join(' → ')).join('\n')+'\n';
let notes='# 明天照常营业 · 思想手记\n\n'+p.intro+'\n\n'+foundation+'\n\n';for(const [i,ch]of p.chapters.entries()){notes+='## 第 '+(i+1)+' 案 · '+ch.name+'\n\n';for(const a of ch.cards)notes+='### '+a.term+'\n\n'+a.de+'\n\n**生活中的入口**：'+a.scene+'\n\n'+a.meaning+'\n\n**避免误读**：'+a.misread+'\n\n**继续追问**：'+a.question+'\n\n阅读位置：'+a.ref+'。\n\n';}notes+='## 继续阅读\n\n海德格尔的重要概念没有公认穷尽的清单。这 32 组主题覆盖主要分析脉络，不能代替原典，也不抹平早晚期思想差异与解释争议。\n\n'+p.sources.map(x=>'- ['+x.name+']('+x.url+')').join('\n')+'\n\n叙事中的公共安排是本作的当代延伸，不冒充海德格尔本人对 AI 的结论。\n';
const esc=x=>x.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');function book(text,title){let toc=[],n=0;const inline=x=>esc(x).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\((https:\/\/[^\s]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1 ↗</a>');let content=text.split(/\n\n/).map(block=>{let m=block.match(/^(#{1,4}) (.*)$/s);if(m){let level=m[1].length,id='s'+n++;if(level===2)toc.push('<a href="#'+id+'">'+esc(m[2])+'</a>');return '<h'+level+' id="'+id+'">'+inline(m[2])+'</h'+level+'>';}if(block.startsWith('- '))return '<ul>'+block.split('\n').map(x=>'<li>'+inline(x.replace(/^- /,''))+'</li>').join('')+'</ul>';return '<p>'+inline(block).replaceAll('\n','<br>')+'</p>';}).join('\n');return '<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+' · 明天照常营业</title><link rel="stylesheet" href="book.css"><header><a href="./">← 返回游戏</a><nav><a href="script.html">完整剧本</a><a href="notes.html">思想手记</a></nav></header><main><details class="contents"><summary>章节目录</summary>'+toc.join('')+'</details>'+content+'</main><footer><a href="./">返回明天照常营业</a></footer></html>';}
for(const [file,text]of [['剧本.md',md],['思想手记.md',notes],['script.html',book(md,'完整剧本')],['notes.html',book(notes,'思想手记')]])fs.writeFileSync(path.join(root,file),text);console.log(JSON.stringify({dialogueBeatsIncludingBranches:beats,scriptCharacters:md.length,notesCharacters:notes.length,maps:Object.keys(w.maps).length}));
